export type GuideEditorial = {
  answerEyebrow: string;
  answerHeading: string;
  scopeLabels: [string, string, string];
  checklistEyebrow: string;
  checklistHeading: string;
  toc: {
    answer: string;
    comparison: string;
    shortlist: string;
    faq: string;
  };
  comparisonEyebrow: string;
  comparisonHeading: string;
  comparisonNote: string;
  selectionEyebrow: string;
  selectionHeading: string;
  selectionNote: string;
  faqHeading: string;
  continueHeading: string;
  relatedGuidesHeading: string;
  feedbackPrompt: string;
};

const guideEditorial: Record<string, GuideEditorial> = {
  'meilleure-prop-firm-2026': {
    answerEyebrow: '2026 verdict',
    answerHeading: 'Which prop firms deserve a place on the first shortlist?',
    scopeLabels: ['Payout reliability', 'Rule clarity', 'Legal evidence'],
    checklistEyebrow: 'Ranking checks',
    checklistHeading: 'Before you trust any prop-firm ranking.',
    toc: { answer: '2026 verdict', comparison: 'Offers compared', shortlist: 'Risk shortlist', faq: 'Ranking questions' },
    comparisonEyebrow: 'Flagship offers',
    comparisonHeading: 'Compare the leading offers on the rules that survive checkout.',
    comparisonNote: 'The useful comparison is payout, drawdown, funded-stage cost and evidence. Account size and discounts come later.',
    selectionEyebrow: 'Risk-first selection',
    selectionHeading: 'Established profiles worth checking first.',
    selectionNote: 'Selected from current PropRadar profiles using risk, source depth and program fit.',
    faqHeading: 'Questions traders ask before trusting a 2026 ranking.',
    continueHeading: 'Continue from ranking to due diligence.',
    relatedGuidesHeading: 'More research for building a safer shortlist.',
    feedbackPrompt: 'Did this ranking make the trade-offs between firms clearer?',
  },
  'meilleure-prop-firm-futures': {
    answerEyebrow: 'Futures verdict',
    answerHeading: 'Which futures funding model is easiest to verify?',
    scopeLabels: ['Trailing vs EOD', 'Activation fees', 'Payout caps'],
    checklistEyebrow: 'Futures checks',
    checklistHeading: 'What to verify beyond the evaluation discount.',
    toc: { answer: 'Futures verdict', comparison: 'Program costs', shortlist: 'Futures shortlist', faq: 'Futures questions' },
    comparisonEyebrow: 'Futures programs',
    comparisonHeading: 'Compare drawdown, funded fees and payout access side by side.',
    comparisonNote: 'A cheap evaluation can become expensive after activation, resets or restricted payouts. Read the full account lifecycle.',
    selectionEyebrow: 'Futures research list',
    selectionHeading: 'Futures firms worth checking line by line.',
    selectionNote: 'Prioritized from futures-compatible profiles with usable payout and source signals.',
    faqHeading: 'Questions to settle before choosing a futures prop firm.',
    continueHeading: 'Continue the futures due diligence.',
    relatedGuidesHeading: 'More futures, payout and drawdown research.',
    feedbackPrompt: 'Did this guide clarify the real cost of futures funding?',
  },
  'prop-firm-sans-consistency-rule': {
    answerEyebrow: 'Rule explained',
    answerHeading: 'What does a consistency rule change at payout?',
    scopeLabels: ['Best-day formula', 'Funded-stage rules', 'Payout eligibility'],
    checklistEyebrow: 'Formula checks',
    checklistHeading: 'Questions to answer before choosing a no-rule account.',
    toc: { answer: 'Rule explained', comparison: 'No-rule programs', shortlist: 'Rule shortlist', faq: 'Formula questions' },
    comparisonEyebrow: 'Consistency comparison',
    comparisonHeading: 'Compare the rule that disappears with the limits that remain.',
    comparisonNote: 'No consistency rule does not remove daily loss, trailing drawdown, minimum days or payout review clauses.',
    selectionEyebrow: 'No-rule candidates',
    selectionHeading: 'Programs to verify for consistency-free payouts.',
    selectionNote: 'Each program must be checked separately because one firm can apply different formulas by account type.',
    faqHeading: 'Practical questions about best-day and consistency rules.',
    continueHeading: 'Check every rule that still applies.',
    relatedGuidesHeading: 'More guidance on drawdown, payouts and funded-stage rules.',
    feedbackPrompt: 'Did this guide make the consistency formula easier to understand?',
  },
  'prop-firm-news-trading': {
    answerEyebrow: 'News-trading answer',
    answerHeading: 'Can you trade NFP, CPI and FOMC without breaking the account?',
    scopeLabels: ['Event windows', 'Funded-stage permission', 'Slippage clauses'],
    checklistEyebrow: 'Event-risk checks',
    checklistHeading: 'What to read before trading a red-folder release.',
    toc: { answer: 'News answer', comparison: 'Event rules', shortlist: 'News-friendly firms', faq: 'News questions' },
    comparisonEyebrow: 'Event-rule comparison',
    comparisonHeading: 'Compare permission, banned windows and payout treatment.',
    comparisonNote: '"News trading allowed" is not enough. Check entries, exits, pending orders, slippage and funded-stage exceptions.',
    selectionEyebrow: 'News-trading shortlist',
    selectionHeading: 'Firms whose exact event rules deserve verification.',
    selectionNote: 'This is a research shortlist, not a permanent whitelist. Official event rules can change by program.',
    faqHeading: 'Questions traders ask before trading high-impact news.',
    continueHeading: 'Verify the event window before checkout.',
    relatedGuidesHeading: 'More research for news, SMC and intraday traders.',
    feedbackPrompt: 'Did this guide clarify what "news trading allowed" really means?',
  },
  'prop-firm-payout-rapide': {
    answerEyebrow: 'Withdrawal verdict',
    answerHeading: 'What makes a payout genuinely fast?',
    scopeLabels: ['Minimum withdrawal', 'Required trading days', 'Incident history'],
    checklistEyebrow: 'Payout checks',
    checklistHeading: 'What to prove before trusting a speed claim.',
    toc: { answer: 'Payout verdict', comparison: 'Withdrawal terms', shortlist: 'Fast-payout shortlist', faq: 'Payout questions' },
    comparisonEyebrow: 'Withdrawal comparison',
    comparisonHeading: 'Compare the advertised delay with the conditions behind it.',
    comparisonNote: 'A 24-hour claim is meaningful only when minimum amounts, caps, reviews and recent payout evidence agree.',
    selectionEyebrow: 'Payout candidates',
    selectionHeading: 'Firms to investigate for faster withdrawals.',
    selectionNote: 'Selected from current profiles using payout timing, incident signals and evidence depth.',
    faqHeading: 'Questions to ask before relying on a fast payout promise.',
    continueHeading: 'Move from payout speed to payout proof.',
    relatedGuidesHeading: 'More withdrawal, evidence and payout-risk research.',
    feedbackPrompt: 'Did this guide help you judge payout speed more critically?',
  },
  'prop-firm-pas-cher': {
    answerEyebrow: 'Cost verdict',
    answerHeading: 'When is a cheap challenge actually good value?',
    scopeLabels: ['Checkout price', 'Funded fees', 'Rebuy risk'],
    checklistEyebrow: 'Budget checks',
    checklistHeading: 'Calculate the total cost before using a coupon.',
    toc: { answer: 'Cost verdict', comparison: 'True cost', shortlist: 'Budget shortlist', faq: 'Price questions' },
    comparisonEyebrow: 'Cost comparison',
    comparisonHeading: 'Compare price after discounts, resets and funded-stage fees.',
    comparisonNote: 'The cheapest checkout is not the cheapest program when strict rules increase resets or failed payout attempts.',
    selectionEyebrow: 'Budget candidates',
    selectionHeading: 'Lower-cost firms that still require a risk check.',
    selectionNote: 'Filtered by entry price, then reviewed against payout risk and current profile quality.',
    faqHeading: 'Questions to answer before buying a cheap challenge.',
    continueHeading: 'Check the cost that appears after checkout.',
    relatedGuidesHeading: 'More research on discounts, direct funding and real cost.',
    feedbackPrompt: 'Did this guide help you calculate cost beyond the discount?',
  },
  'prop-firm-smc-ict': {
    answerEyebrow: 'SMC / ICT fit',
    answerHeading: 'Which rules protect an SMC / ICT execution plan?',
    scopeLabels: ['Session timing', 'Scaling entries', 'Drawdown behavior'],
    checklistEyebrow: 'Strategy checks',
    checklistHeading: 'Test the rules against your actual execution.',
    toc: { answer: 'Strategy fit', comparison: 'SMC-compatible rules', shortlist: 'SMC shortlist', faq: 'SMC questions' },
    comparisonEyebrow: 'Strategy comparison',
    comparisonHeading: 'Compare the programs that can handle liquidity-based trading.',
    comparisonNote: 'Focus on news windows, scaling, spreads, indices, drawdown and payout minimums during London and New York sessions.',
    selectionEyebrow: 'SMC / ICT candidates',
    selectionHeading: 'Firms to test against your session and risk model.',
    selectionNote: 'Selected for intraday compatibility, then weighted by payout and rule evidence.',
    faqHeading: 'Questions SMC and ICT traders should settle before buying.',
    continueHeading: 'Match the program to the setup, not the label.',
    relatedGuidesHeading: 'More research for SMC, news and intraday execution.',
    feedbackPrompt: 'Did this guide help you match prop-firm rules to SMC / ICT trading?',
  },
  'prop-firm-swing-trading': {
    answerEyebrow: 'Swing-trading fit',
    answerHeading: 'Can you hold overnight and through the weekend?',
    scopeLabels: ['Overnight holding', 'Weekend gaps', 'Rollover rules'],
    checklistEyebrow: 'Holding checks',
    checklistHeading: 'Verify what happens while the trade stays open.',
    toc: { answer: 'Holding answer', comparison: 'Swing rules', shortlist: 'Swing shortlist', faq: 'Holding questions' },
    comparisonEyebrow: 'Swing comparison',
    comparisonHeading: 'Compare holding permission, gap risk and drawdown.',
    comparisonNote: 'A program built for intraday trading can become unsuitable when positions cross rollover, news or the weekend.',
    selectionEyebrow: 'Swing candidates',
    selectionHeading: 'Firms to verify for longer holding periods.',
    selectionNote: 'Filtered for swing-related permissions and checked against current payout risk.',
    faqHeading: 'Questions to settle before holding a funded trade overnight.',
    continueHeading: 'Read the holding rule for both account stages.',
    relatedGuidesHeading: 'More research on news, drawdown and longer-term trades.',
    feedbackPrompt: 'Did this guide clarify overnight and weekend holding risk?',
  },
  'prop-firm-ea-algo': {
    answerEyebrow: 'Automation verdict',
    answerHeading: 'Which automation rules can block an otherwise allowed EA?',
    scopeLabels: ['EA permission', 'Copy trading', 'Latency restrictions'],
    checklistEyebrow: 'Automation checks',
    checklistHeading: 'Read the prohibited-strategy clauses before deployment.',
    toc: { answer: 'Automation answer', comparison: 'EA rules', shortlist: 'Algo shortlist', faq: 'EA questions' },
    comparisonEyebrow: 'Automation comparison',
    comparisonHeading: 'Compare EA permission with the restrictions around it.',
    comparisonNote: 'Bots can be allowed while copy trading, latency, arbitrage, grid or multi-account behavior remains prohibited.',
    selectionEyebrow: 'EA / algo candidates',
    selectionHeading: 'Firms whose automation terms need a line-by-line check.',
    selectionNote: 'Selected from automation-compatible profiles with acceptable current payout signals.',
    faqHeading: 'Questions algo traders should answer before connecting an EA.',
    continueHeading: 'Validate the exact strategy, VPS and account setup.',
    relatedGuidesHeading: 'More research on rules, platforms and payout validation.',
    feedbackPrompt: 'Did this guide clarify the difference between EA permission and EA safety?',
  },
  'prop-firm-fiable-trustpilot': {
    answerEyebrow: 'Reliability test',
    answerHeading: 'What separates a reliable firm from a highly rated one?',
    scopeLabels: ['Source coherence', 'Payout history', 'Legal transparency'],
    checklistEyebrow: 'Trust checks',
    checklistHeading: 'Build the evidence file before trusting the score.',
    toc: { answer: 'Reliability test', comparison: 'Trust signals', shortlist: 'Reliable profiles', faq: 'Trust questions' },
    comparisonEyebrow: 'Evidence comparison',
    comparisonHeading: 'Compare ratings with payouts, rules and legal sources.',
    comparisonNote: 'Trustpilot is one signal. Reliability improves when independent sources, community reports and official terms tell the same story.',
    selectionEyebrow: 'Evidence-led selection',
    selectionHeading: 'Profiles with stronger public evidence to examine first.',
    selectionNote: 'Prioritized using source depth, review reliability, payout risk and current operating status.',
    faqHeading: 'Questions to ask before calling a prop firm reliable.',
    continueHeading: 'Cross-check the rating with harder evidence.',
    relatedGuidesHeading: 'More research on reviews, payout proof and legal checks.',
    feedbackPrompt: 'Did this guide improve the way you assess prop-firm reliability?',
  },
  'ftmo-vs-the5ers': {
    answerEyebrow: 'Head-to-head verdict',
    answerHeading: 'FTMO or The5ers: which profile fits your constraints?',
    scopeLabels: ['Program structure', 'Scaling path', 'Payout conditions'],
    checklistEyebrow: 'Match checks',
    checklistHeading: 'Compare the exact programs, not only the brands.',
    toc: { answer: 'Match verdict', comparison: 'FTMO vs The5ers', shortlist: 'Decision signals', faq: 'Match questions' },
    comparisonEyebrow: 'Direct comparison',
    comparisonHeading: 'Put FTMO and The5ers flagship programs side by side.',
    comparisonNote: 'The decision depends on drawdown, target, platform, scaling and funded-stage rules more than brand popularity.',
    selectionEyebrow: 'Decision context',
    selectionHeading: 'The profiles and alternatives worth opening next.',
    selectionNote: 'Use the two firm files first, then benchmark only alternatives that solve a concrete constraint.',
    faqHeading: 'Questions traders ask when choosing FTMO or The5ers.',
    continueHeading: 'Open the exact firm files before deciding.',
    relatedGuidesHeading: 'More FTMO, The5ers and forex comparisons.',
    feedbackPrompt: 'Did this comparison make the FTMO vs The5ers decision clearer?',
  },
  'topstep-vs-apex': {
    answerEyebrow: 'Futures match verdict',
    answerHeading: 'Topstep or Apex: where does the real cost sit?',
    scopeLabels: ['Trailing threshold', 'Funded fees', 'Payout access'],
    checklistEyebrow: 'Futures match checks',
    checklistHeading: 'Compare the full path from evaluation to withdrawal.',
    toc: { answer: 'Match verdict', comparison: 'Topstep vs Apex', shortlist: 'Decision signals', faq: 'Match questions' },
    comparisonEyebrow: 'Direct futures comparison',
    comparisonHeading: 'Compare payout rules before evaluation discounts.',
    comparisonNote: 'Monthly cost, activation, drawdown and payout caps can matter more than the advertised account size.',
    selectionEyebrow: 'Futures decision set',
    selectionHeading: 'Topstep, Apex and the benchmarks worth checking.',
    selectionNote: 'Open the current firm files because pricing and funded-stage rules can change quickly.',
    faqHeading: 'Questions traders ask before choosing Topstep or Apex.',
    continueHeading: 'Validate current costs and payout terms.',
    relatedGuidesHeading: 'More futures funding and payout comparisons.',
    feedbackPrompt: 'Did this guide clarify the true Topstep vs Apex cost?',
  },
  'funderpro-vs-the5ers': {
    answerEyebrow: 'Forex match verdict',
    answerHeading: 'FunderPro or The5ers: flexibility or longer history?',
    scopeLabels: ['Rule flexibility', 'Operating history', 'Payout rhythm'],
    checklistEyebrow: 'Match checks',
    checklistHeading: 'Decide which trade-off matters for your strategy.',
    toc: { answer: 'Match verdict', comparison: 'FunderPro vs The5ers', shortlist: 'Decision signals', faq: 'Match questions' },
    comparisonEyebrow: 'Direct comparison',
    comparisonHeading: 'Compare flexibility with the strength of the public record.',
    comparisonNote: 'A newer flexible offer should be weighed against payout evidence, rule clarity and the longer track record of its competitor.',
    selectionEyebrow: 'Forex decision set',
    selectionHeading: 'FunderPro, The5ers and relevant benchmarks.',
    selectionNote: 'Use the selected profiles to test price, platforms, news, EA and payout conditions.',
    faqHeading: 'Questions traders ask before choosing FunderPro or The5ers.',
    continueHeading: 'Check the exact offer behind each brand.',
    relatedGuidesHeading: 'More forex, flexibility and payout comparisons.',
    feedbackPrompt: 'Did this guide clarify the FunderPro vs The5ers trade-off?',
  },
  'leveraged-prop-firm-avis': {
    answerEyebrow: 'Risk review',
    answerHeading: 'Is Get Leveraged worth the legal and payout risk?',
    scopeLabels: ['CySEC warning', '20% consistency', 'Recent payout proof'],
    checklistEyebrow: 'High-vigilance checks',
    checklistHeading: 'Evidence required before considering a purchase.',
    toc: { answer: 'Risk verdict', comparison: 'Program claims', shortlist: 'Evidence file', faq: 'Review questions' },
    comparisonEyebrow: 'Offer verification',
    comparisonHeading: 'Compare the program claims with the current risk file.',
    comparisonNote: 'A recent operator with a regulator warning to verify requires stronger legal, rule and payout evidence than an established firm.',
    selectionEyebrow: 'Risk context',
    selectionHeading: 'Profiles to use as safer comparison benchmarks.',
    selectionNote: 'Benchmarks are provided to compare operating history, source depth and payout risk.',
    faqHeading: 'Questions to answer before buying from Get Leveraged.',
    continueHeading: 'Verify the regulator record and recent payouts first.',
    relatedGuidesHeading: 'More legal, payout-proof and reliability research.',
    feedbackPrompt: 'Did this review make the Get Leveraged risk file clearer?',
  },
  'goat-funded-trader-avis': {
    answerEyebrow: 'GFT verdict',
    answerHeading: 'Which Goat Funded Trader model should you verify first?',
    scopeLabels: ['Model-specific rules', 'News and holding', 'Payout delay'],
    checklistEyebrow: 'GFT checks',
    checklistHeading: 'Choose the model before applying the discount.',
    toc: { answer: 'GFT verdict', comparison: 'GFT models', shortlist: 'Decision signals', faq: 'GFT questions' },
    comparisonEyebrow: 'GFT program comparison',
    comparisonHeading: 'Compare 1-step, 2-step, 3-step and Instant conditions.',
    comparisonNote: 'The brand-level offer is too broad to decide from. News, holding, loss limits and payouts can differ by model.',
    selectionEyebrow: 'GFT research context',
    selectionHeading: 'GFT and comparable profiles to investigate.',
    selectionNote: 'Use the GFT file first, then compare alternatives with similar speed or flexibility.',
    faqHeading: 'Questions to settle before choosing a GFT model.',
    continueHeading: 'Confirm the model rules before using a code.',
    relatedGuidesHeading: 'More research on GFT, instant funding and discounts.',
    feedbackPrompt: 'Did this review help you distinguish the different GFT models?',
  },
  'prop-firm-instant-funding': {
    answerEyebrow: 'Instant-access verdict',
    answerHeading: 'Does instant funding save time or simply move the test?',
    scopeLabels: ['Upfront cost', 'Funded-stage limits', 'Withdrawal access'],
    checklistEyebrow: 'Instant-account checks',
    checklistHeading: 'Read the funded rules before paying for speed.',
    toc: { answer: 'Instant verdict', comparison: 'Direct accounts', shortlist: 'Instant shortlist', faq: 'Instant questions' },
    comparisonEyebrow: 'Instant funding comparison',
    comparisonHeading: 'Compare speed with cost, drawdown and payout limits.',
    comparisonNote: 'Skipping an evaluation does not remove the test. It moves the difficulty into funded-stage risk and withdrawal rules.',
    selectionEyebrow: 'Instant candidates',
    selectionHeading: 'Direct-access programs worth a closer rule check.',
    selectionNote: 'Selected from instant and direct-funded profiles with acceptable current payout signals.',
    faqHeading: 'Questions to ask before paying for instant funding.',
    continueHeading: 'Decide whether speed justifies the tighter rules.',
    relatedGuidesHeading: 'More direct funding, no-challenge and payout research.',
    feedbackPrompt: 'Did this guide clarify the real trade-off in instant funding?',
  },
  'prop-firm-sans-challenge': {
    answerEyebrow: 'Direct-funding verdict',
    answerHeading: 'Who should actually consider a no-challenge account?',
    scopeLabels: ['Direct access', 'Tighter drawdown', 'True 3-month cost'],
    checklistEyebrow: 'Direct-funding checks',
    checklistHeading: 'Test your strategy against funded-stage rules first.',
    toc: { answer: 'Direct-funding answer', comparison: 'No-challenge offers', shortlist: 'Direct shortlist', faq: 'No-challenge questions' },
    comparisonEyebrow: 'Direct funding comparison',
    comparisonHeading: 'Compare no-challenge offers by the rules that govern payout.',
    comparisonNote: 'The shortcut is useful only when your strategy is already stable enough to survive the funded-stage constraints.',
    selectionEyebrow: 'Direct-funding candidates',
    selectionHeading: 'No-challenge programs to verify before paying.',
    selectionNote: 'Filtered from direct and instant profiles, then weighted by cost, payout risk and evidence.',
    faqHeading: 'Questions traders ask before skipping the evaluation.',
    continueHeading: 'Check whether direct access fits your real risk profile.',
    relatedGuidesHeading: 'More instant funding, beginner and payout research.',
    feedbackPrompt: 'Did this guide help you decide whether no-challenge funding fits you?',
  },
  'prop-firm-pour-debutant': {
    answerEyebrow: 'Beginner verdict',
    answerHeading: 'What should a beginner buy first, if anything?',
    scopeLabels: ['Readable rules', 'Smaller account', 'Learning cost'],
    checklistEyebrow: 'First-challenge checks',
    checklistHeading: 'Protect the learning curve before chasing scale.',
    toc: { answer: 'Beginner answer', comparison: 'First programs', shortlist: 'Beginner shortlist', faq: 'Beginner questions' },
    comparisonEyebrow: 'Beginner program comparison',
    comparisonHeading: 'Compare clear rules, manageable cost and realistic drawdown.',
    comparisonNote: 'A first account should teach rule discipline without pushing the trader into oversized risk or repeated rebuying.',
    selectionEyebrow: 'Beginner candidates',
    selectionHeading: 'Firms with clearer starting points to investigate.',
    selectionNote: 'Selected using cost, score, payout risk and the readability of the current profile.',
    faqHeading: 'Questions new traders should answer before a first challenge.',
    continueHeading: 'Start smaller and verify every rule.',
    relatedGuidesHeading: 'More beginner, budget and rule-reading guidance.',
    feedbackPrompt: 'Did this guide help you plan a safer first prop-firm challenge?',
  },
  'meilleure-prop-firm-forex': {
    answerEyebrow: 'Forex verdict',
    answerHeading: 'Which forex prop firm fits your platform and execution?',
    scopeLabels: ['MT5 / cTrader', 'Spreads and news', 'Payout record'],
    checklistEyebrow: 'Forex checks',
    checklistHeading: 'Test the trading environment before the discount.',
    toc: { answer: 'Forex verdict', comparison: 'Forex programs', shortlist: 'Forex shortlist', faq: 'Forex questions' },
    comparisonEyebrow: 'Forex program comparison',
    comparisonHeading: 'Compare platforms, execution rules and withdrawals.',
    comparisonNote: 'The useful forex choice starts with symbols, spreads, platform, news and EA rules before account size.',
    selectionEyebrow: 'Forex candidates',
    selectionHeading: 'Forex-focused firms worth checking first.',
    selectionNote: 'Filtered for forex, CFD and relevant platform signals, then weighted by payout risk.',
    faqHeading: 'Questions to settle before choosing a forex prop firm.',
    continueHeading: 'Verify execution and funded-stage rules.',
    relatedGuidesHeading: 'More forex, FTMO and trading-style research.',
    feedbackPrompt: 'Did this guide clarify which forex criteria matter most?',
  },
  'alternatives-ftmo': {
    answerEyebrow: 'Switching verdict',
    answerHeading: 'When does leaving FTMO make practical sense?',
    scopeLabels: ['Concrete pain point', 'Rule flexibility', 'Payout trade-off'],
    checklistEyebrow: 'Switching checks',
    checklistHeading: 'Name the problem the alternative must solve.',
    toc: { answer: 'Switching verdict', comparison: 'FTMO alternatives', shortlist: 'Alternative shortlist', faq: 'Switching questions' },
    comparisonEyebrow: 'Alternative comparison',
    comparisonHeading: 'Compare FTMO alternatives by the constraint they solve.',
    comparisonNote: 'Price alone is not a reason to switch. The alternative should improve platform fit, rules, payout timing or scaling.',
    selectionEyebrow: 'Alternative candidates',
    selectionHeading: 'Firms to benchmark against FTMO.',
    selectionNote: 'Selected for common FTMO pain points, then checked against payout and evidence quality.',
    faqHeading: 'Questions to answer before moving away from FTMO.',
    continueHeading: 'Compare the exact alternative with the FTMO baseline.',
    relatedGuidesHeading: 'More FTMO comparisons and forex research.',
    feedbackPrompt: 'Did this guide help you identify a valid reason to leave FTMO?',
  },
  'prop-firm-avis-reddit-trustpilot': {
    answerEyebrow: 'Review-reading verdict',
    answerHeading: 'How do you separate useful trader evidence from review noise?',
    scopeLabels: ['Review timing', 'Platform coherence', 'Payout complaints'],
    checklistEyebrow: 'Review checks',
    checklistHeading: 'Read the pattern behind the public score.',
    toc: { answer: 'Review method', comparison: 'Signal table', shortlist: 'Profiles to inspect', faq: 'Review questions' },
    comparisonEyebrow: 'Review-signal comparison',
    comparisonHeading: 'Compare Trustpilot with Reddit, Discord and payout evidence.',
    comparisonNote: 'A high rating becomes useful only when recent community reports, exact rules and withdrawal outcomes remain coherent.',
    selectionEyebrow: 'Review research set',
    selectionHeading: 'Profiles that show why cross-platform reading matters.',
    selectionNote: 'Selected for visible review volume and enough public context to compare signals.',
    faqHeading: 'Questions to ask when a prop firm has an excellent rating.',
    continueHeading: 'Move from public rating to verifiable evidence.',
    relatedGuidesHeading: 'More research on Trustpilot, payout proof and reliability.',
    feedbackPrompt: 'Did this guide improve the way you read prop-firm reviews?',
  },
  'prop-firm-payout-proof': {
    answerEyebrow: 'Evidence standard',
    answerHeading: 'What counts as credible prop-firm payout proof?',
    scopeLabels: ['Dated evidence', 'Exact program', 'Independent repetition'],
    checklistEyebrow: 'Proof checks',
    checklistHeading: 'Authenticate the context, not only the screenshot.',
    toc: { answer: 'Proof standard', comparison: 'Evidence profiles', shortlist: 'Proof shortlist', faq: 'Proof questions' },
    comparisonEyebrow: 'Payout evidence comparison',
    comparisonHeading: 'Compare withdrawal claims with rules and incident history.',
    comparisonNote: 'Strong proof is dated, tied to a program, consistent with official terms and repeated outside firm marketing.',
    selectionEyebrow: 'Evidence candidates',
    selectionHeading: 'Firms with payout proof worth checking in context.',
    selectionNote: 'Filtered from profiles carrying payout evidence and acceptable current withdrawal risk.',
    faqHeading: 'Questions to ask before trusting a payout screenshot.',
    continueHeading: 'Cross-check the proof with the withdrawal rules.',
    relatedGuidesHeading: 'More payout, review and incident research.',
    feedbackPrompt: 'Did this guide help you judge payout proof more rigorously?',
  },
  'prop-firm-legal-check': {
    answerEyebrow: 'Legal due diligence',
    answerHeading: 'Which legal entity are you actually contracting with?',
    scopeLabels: ['Contracting entity', 'Regulatory perimeter', 'Dispute clauses'],
    checklistEyebrow: 'Legal checks',
    checklistHeading: 'Verify the company before evaluating the offer.',
    toc: { answer: 'Legal answer', comparison: 'Entity files', shortlist: 'Legal watchlist', faq: 'Legal questions' },
    comparisonEyebrow: 'Legal file comparison',
    comparisonHeading: 'Compare entity clarity, sources and contractual risk.',
    comparisonNote: 'Company registration is only the start. Check the simulated-account model, jurisdiction, restrictions and payout-forfeiture language.',
    selectionEyebrow: 'Legal research set',
    selectionHeading: 'Firm files to open for entity and source checks.',
    selectionNote: 'Prioritized from current profiles using legal mapping, source depth and regulatory risk.',
    faqHeading: 'Questions to ask before accepting prop-firm terms.',
    continueHeading: 'Read the legal entity and dispute terms before checkout.',
    relatedGuidesHeading: 'More legal, reliability and payout-risk research.',
    feedbackPrompt: 'Did this guide make the legal checks easier to perform?',
  },
};

const fallbackEditorial: GuideEditorial = {
  answerEyebrow: 'Direct answer',
  answerHeading: 'What should you verify before making this decision?',
  scopeLabels: ['Current rules', 'Payout risk', 'Source quality'],
  checklistEyebrow: 'Decision checks',
  checklistHeading: 'Points to verify before checkout.',
  toc: { answer: 'Direct answer', comparison: 'Comparison', shortlist: 'Shortlist', faq: 'Questions' },
  comparisonEyebrow: 'Program comparison',
  comparisonHeading: 'Compare the current programs before choosing.',
  comparisonNote: 'Prices and rules can change. Verify the exact offer on the official page before purchase.',
  selectionEyebrow: 'Research shortlist',
  selectionHeading: 'Firms to investigate for this decision.',
  selectionNote: 'Selection calculated from current PropRadar profiles and risk signals.',
  faqHeading: 'Questions to answer before deciding.',
  continueHeading: 'Continue the due diligence.',
  relatedGuidesHeading: 'More research for the next decision.',
  feedbackPrompt: 'Did this guide help you make a clearer decision?',
};

export function getGuideEditorial(slug: string) {
  return guideEditorial[slug] ?? fallbackEditorial;
}

export function hasCustomGuideEditorial(slug: string) {
  return Object.prototype.hasOwnProperty.call(guideEditorial, slug);
}
