export type Product = {
  id: string;
  name: string;
  type: 'Challenge' | 'Instant funding' | 'Futures evaluation' | 'Scaling';
  description: string;
  accountSizeMin: number;
  accountSizeMax: number;
  entryFeeMin?: number;
  entryFeeMax?: number;
  profitTarget: string;
  maxDailyLoss: string;
  maxDrawdown: string;
  profitSplit: string;
  platforms: string[];
  tradableAssets: string[];
  minTradingDays?: string;
  hasConsistencyRule: boolean;
  consistencyRule?: string;
  linkToStart?: string;
  isPopular?: boolean;
};

export type SourceLink = {
  label: string;
  url: string;
};

export type ReviewSignals = {
  redditScore: number;
  redditMentions: string;
  redditSignal: 'Positif' | 'Mixte' | 'Négatif' | 'Faible volume';
  trustpilotReliabilityScore: number;
  trustpilotReliability: 'Forte' | 'Moyenne' | 'Faible';
  trustpilotNote: string;
  payoutRiskScore: number;
  payoutRisk: 'Faible' | 'Modéré' | 'Élevé' | 'Critique';
  payoutIssues: string[];
  lastSignalCheck: string;
};

export type PropFirm = {
  id: number;
  slug: string;
  name: string;
  status: 'Active' | 'À surveiller' | 'Fermée';
  score: number;
  founded: number;
  headquarters: string;
  bestFor: string;
  verdict: string;
  priceFrom: number;
  profitSplit: number;
  drawdownType: 'EOD' | 'Trailing' | 'Static' | 'Hybride';
  newsTrading: 'Autorisé' | 'Restreint' | 'Non recommandé' | 'Variable';
  eaAllowed: 'Oui' | 'Non' | 'Sur demande' | 'Variable';
  payoutDelay: string;
  incidents: number;
  incidentsDetails: string[];
  styles: string[];
  legalVerified: boolean;
  transparencyScore: number;
  payoutProof: boolean;
  recentRuleChange: boolean;
  lastReviewed: string;
  trustpilotRating?: number;
  logoDomain?: string;
  communitySignal: string;
  products: Product[];
  strengths: string[];
  weaknesses: string[];
  sources: SourceLink[];
  commercialRelationship: 'Aucune' | 'Affiliation transparente';
  commercialNote?: string;
  reviewSignals: ReviewSignals;
};

const REVIEW_DATE = '2026-06-29';
const FTMO_AFFILIATE_URL = 'https://trader.ftmo.com/?affiliates=ILTDLLkYLwdMlzGLBwkq';

type ProductInput = Pick<Product, 'id' | 'name' | 'description'> & Partial<Omit<Product, 'id' | 'name' | 'description'>>;

function product(data: ProductInput): Product {
  return {
    type: 'Challenge',
    accountSizeMin: 5000,
    accountSizeMax: 200000,
    profitTarget: 'variable selon programme',
    maxDailyLoss: 'variable',
    maxDrawdown: 'variable',
    profitSplit: 'variable',
    platforms: ['À vérifier'],
    tradableAssets: ['À vérifier'],
    hasConsistencyRule: true,
    consistencyRule: 'Règles à vérifier sur la page officielle du produit.',
    ...data,
  };
}

type FirmInput = Omit<
  PropFirm,
  | 'lastReviewed'
  | 'incidentsDetails'
  | 'styles'
  | 'legalVerified'
  | 'transparencyScore'
  | 'payoutProof'
  | 'recentRuleChange'
  | 'trustpilotRating'
  | 'logoDomain'
  | 'products'
  | 'strengths'
  | 'weaknesses'
  | 'sources'
  | 'commercialRelationship'
  | 'commercialNote'
  | 'reviewSignals'
> &
  Partial<
    Pick<
      PropFirm,
      | 'lastReviewed'
      | 'incidentsDetails'
      | 'styles'
      | 'legalVerified'
      | 'transparencyScore'
      | 'payoutProof'
      | 'recentRuleChange'
      | 'trustpilotRating'
      | 'logoDomain'
      | 'products'
      | 'strengths'
      | 'weaknesses'
      | 'sources'
      | 'commercialRelationship'
      | 'commercialNote'
      | 'reviewSignals'
    >
  >;

function payoutRiskLabel(score: number): ReviewSignals['payoutRisk'] {
  if (score >= 85) return 'Critique';
  if (score >= 65) return 'Élevé';
  if (score >= 40) return 'Modéré';
  return 'Faible';
}

function trustpilotReliabilityLabel(score: number): ReviewSignals['trustpilotReliability'] {
  if (score >= 75) return 'Forte';
  if (score >= 50) return 'Moyenne';
  return 'Faible';
}

function redditSignal(score: number): ReviewSignals['redditSignal'] {
  if (score >= 75) return 'Positif';
  if (score >= 55) return 'Mixte';
  return 'Négatif';
}

function buildReviewSignals(data: Omit<PropFirm, 'reviewSignals'>): ReviewSignals {
  const payoutRiskScore = Math.min(
    100,
    Math.max(
      10,
      data.status === 'Fermée'
        ? 96
        : data.incidents * 14 + (data.payoutProof ? 12 : 28) + (data.recentRuleChange ? 12 : 0)
    )
  );
  const redditScore = Math.max(5, Math.min(95, data.score - data.incidents * 3 - (data.status === 'Fermée' ? 22 : 0)));
  const trustpilotReliabilityScore = Math.max(
    10,
    Math.min(
      92,
      data.transparencyScore * 4 +
        (data.trustpilotRating ? Math.round(data.trustpilotRating * 4) : 8) +
        (data.payoutProof ? 8 : -8) -
        data.incidents * 5
    )
  );

  return {
    redditScore,
    redditMentions: data.status === 'Fermée' ? 'archives et alertes historiques' : data.incidents >= 3 ? 'volume élevé de plaintes à trier' : 'volume public à surveiller',
    redditSignal: redditSignal(redditScore),
    trustpilotReliabilityScore,
    trustpilotReliability: trustpilotReliabilityLabel(trustpilotReliabilityScore),
    trustpilotNote: data.trustpilotRating
      ? `Trustpilot ${data.trustpilotRating}/5, à pondérer avec Reddit, forums et preuves de payout.`
      : 'Pas assez de données Trustpilot robustes : pondération faible dans le radar.',
    payoutRiskScore,
    payoutRisk: payoutRiskLabel(payoutRiskScore),
    payoutIssues: data.incidentsDetails,
    lastSignalCheck: data.lastReviewed,
  };
}

function firm(data: FirmInput): PropFirm {
  const { reviewSignals, ...firmData } = data;
  const base: Omit<PropFirm, 'reviewSignals'> = {
    lastReviewed: REVIEW_DATE,
    incidentsDetails: ['Règles, conditions commerciales et statuts à revérifier avant achat.'],
    styles: ['Forex'],
    legalVerified: true,
    transparencyScore: 12,
    payoutProof: false,
    recentRuleChange: true,
    logoDomain: undefined,
    trustpilotRating: undefined,
    products: [],
    strengths: ['Offre identifiable', 'Sources officielles disponibles'],
    weaknesses: ['Règles susceptibles de changer', 'Données à revérifier avant achat'],
    sources: [],
    commercialRelationship: 'Aucune',
    ...firmData,
  };

  return {
    ...base,
    reviewSignals: reviewSignals ?? buildReviewSignals(base),
  };
}

export const propFirms: PropFirm[] = [
  firm({
    id: 1,
    slug: 'ftmo',
    name: 'FTMO',
    status: 'Active',
    score: 91,
    founded: 2015,
    headquarters: 'République tchèque',
    bestFor: 'traders forex/CFD qui veulent un acteur historique',
    verdict: 'Référence du secteur, très suivie, avec une structure de challenge claire et une réputation solide.',
    priceFrom: 155,
    profitSplit: 80,
    drawdownType: 'EOD',
    newsTrading: 'Restreint',
    eaAllowed: 'Oui',
    payoutDelay: 'souvent 1 à 3 jours ouvrés',
    incidents: 1,
    transparencyScore: 19,
    payoutProof: true,
    recentRuleChange: false,
    trustpilotRating: 4.6,
    logoDomain: 'ftmo.com',
    communitySignal: 'Très forte visibilité, beaucoup de retours vérifiables et d’analyses tierces.',
    commercialRelationship: 'Affiliation transparente',
    commercialNote: 'PropRadar peut recevoir une commission si tu passes par ce lien. Le score reste indépendant et les points faibles restent affichés.',
    reviewSignals: {
      redditScore: 86,
      redditMentions: 'volume élevé, retours globalement stables, plaintes surtout liées aux règles ou vérifications',
      redditSignal: 'Positif',
      trustpilotReliabilityScore: 82,
      trustpilotReliability: 'Forte',
      trustpilotNote: 'Note publique élevée et volume important, mais les avis restent pondérés par Reddit, sources officielles et incidents.',
      payoutRiskScore: 22,
      payoutRisk: 'Faible',
      payoutIssues: ['Peu de signaux récurrents de non-payout ; les litiges visibles concernent surtout l’interprétation des règles.'],
      lastSignalCheck: REVIEW_DATE,
    },
    products: [
      product({
        id: 'ftmo-challenge',
        name: 'FTMO Challenge',
        description: 'Évaluation en une ou deux étapes avec objectifs de profit et limites de perte.',
        accountSizeMin: 10000,
        accountSizeMax: 200000,
        entryFeeMin: 155,
        entryFeeMax: 1080,
        profitTarget: '10% puis 5% sur le modèle 2 étapes',
        maxDailyLoss: '5%',
        maxDrawdown: '10%',
        profitSplit: '80% à 90%',
        platforms: ['MT4', 'MT5', 'cTrader', 'DXtrade'],
        tradableAssets: ['Forex', 'Indices', 'Matières premières', 'Crypto', 'Actions CFD'],
        minTradingDays: '4 jours minimum sur certains modèles',
        hasConsistencyRule: false,
        consistencyRule: undefined,
        linkToStart: FTMO_AFFILIATE_URL,
        isPopular: true,
      }),
    ],
    strengths: ['Marque installée', 'Règles détaillées', 'Bon niveau de transparence', 'Nombreux retours publics'],
    weaknesses: ['Prix plus élevé que certains concurrents', 'Restrictions autour des news et stratégies copiées à vérifier'],
    sources: [
      { label: 'Site officiel FTMO', url: 'https://ftmo.com/' },
      { label: 'Objectifs de trading FTMO', url: 'https://ftmo.com/en/trading-objectives/' },
      { label: 'FAQ FTMO', url: 'https://ftmo.com/en/faq/' },
    ],
  }),
  firm({
    id: 2,
    slug: 'the5ers',
    name: 'The5ers',
    status: 'Active',
    score: 85,
    founded: 2016,
    headquarters: 'Israël',
    bestFor: 'traders prudents qui aiment les limites statiques',
    verdict: 'Profil sérieux avec plusieurs parcours, apprécié par les traders qui privilégient la gestion du risque.',
    priceFrom: 39,
    profitSplit: 80,
    drawdownType: 'Static',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'souvent quelques jours ouvrés',
    incidents: 1,
    transparencyScore: 17,
    payoutProof: true,
    recentRuleChange: true,
    trustpilotRating: 4.4,
    logoDomain: 'the5ers.com',
    communitySignal: 'Bonne réputation, surtout chez les traders conservateurs.',
    products: [
      product({
        id: 'the5ers-high-stakes',
        name: 'High Stakes',
        description: 'Programme en deux phases avec objectifs progressifs et limites de perte strictes.',
        accountSizeMin: 5000,
        accountSizeMax: 100000,
        entryFeeMin: 39,
        entryFeeMax: 495,
        profitTarget: '8% puis 5%',
        maxDailyLoss: '5%',
        maxDrawdown: '10%',
        profitSplit: '80% à 100% selon scaling',
        platforms: ['MT5', 'cTrader'],
        tradableAssets: ['Forex', 'Indices', 'Matières premières'],
        hasConsistencyRule: false,
        consistencyRule: undefined,
        linkToStart: 'https://the5ers.com/',
        isPopular: true,
      }),
    ],
    strengths: ['Drawdown souvent lisible', 'Programmes variés', 'Orientation risque stricte'],
    weaknesses: ['Règles différentes selon programme', 'Moins flexible pour certains profils news/scalping'],
    sources: [
      { label: 'Site officiel The5ers', url: 'https://the5ers.com/' },
      { label: 'Programmes The5ers', url: 'https://the5ers.com/programs/' },
    ],
  }),
  firm({
    id: 3,
    slug: 'fundednext',
    name: 'FundedNext',
    status: 'Active',
    score: 79,
    founded: 2022,
    headquarters: 'Émirats arabes unis',
    bestFor: 'traders qui veulent plusieurs modèles de challenge',
    verdict: 'Acteur très visible avec des offres agressives, intéressant mais à suivre de près côté règles et promos.',
    priceFrom: 59,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'annoncé rapide selon modèle',
    incidents: 2,
    transparencyScore: 15,
    payoutProof: true,
    trustpilotRating: 4.5,
    logoDomain: 'fundednext.com',
    communitySignal: 'Très présent dans la communauté, avis nombreux mais à filtrer.',
    products: [
      product({
        id: 'fundednext-evaluation',
        name: 'Evaluation',
        description: 'Challenge CFD avec plusieurs tailles, modèles et conditions de payout.',
        entryFeeMin: 59,
        entryFeeMax: 999,
        profitSplit: 'jusqu’à 90% selon conditions',
        platforms: ['MT4', 'MT5', 'cTrader'],
        tradableAssets: ['Forex', 'Indices', 'Métaux', 'Crypto'],
        linkToStart: 'https://fundednext.com/',
        isPopular: true,
      }),
    ],
    strengths: ['Prix d’entrée attractifs', 'Plusieurs modèles', 'Forte visibilité internationale'],
    weaknesses: ['Complexité des règles', 'Promotions fréquentes à vérifier', 'Risque de confusion entre modèles'],
    sources: [
      { label: 'Site officiel FundedNext', url: 'https://fundednext.com/' },
      { label: 'FAQ FundedNext', url: 'https://help.fundednext.com/' },
    ],
  }),
  firm({
    id: 4,
    slug: 'topstep',
    name: 'Topstep',
    status: 'Active',
    score: 84,
    founded: 2012,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui veulent un acteur ancien',
    verdict: 'Un des noms historiques du funded trading futures, avec un cadre plus institutionnel que beaucoup de concurrents récents.',
    priceFrom: 49,
    profitSplit: 90,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable selon compte et règles',
    incidents: 1,
    transparencyScore: 17,
    payoutProof: true,
    recentRuleChange: false,
    logoDomain: 'topstep.com',
    communitySignal: 'Très connu côté futures, avec beaucoup de contenu pédagogique.',
    styles: ['Futures', 'Intraday', 'Scalping'],
    products: [
      product({
        id: 'topstep-trading-combine',
        name: 'Trading Combine',
        type: 'Futures evaluation',
        description: 'Évaluation futures avec règles de perte, objectifs et passage vers compte financé.',
        accountSizeMin: 50000,
        accountSizeMax: 150000,
        entryFeeMin: 49,
        entryFeeMax: 149,
        maxDrawdown: 'trailing',
        profitSplit: 'jusqu’à 90%',
        platforms: ['TopstepX', 'NinjaTrader', 'Tradovate'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://www.topstep.com/',
        isPopular: true,
      }),
    ],
    strengths: ['Ancienneté', 'Spécialiste futures', 'Formation et cadre assez documentés'],
    weaknesses: ['Règles de drawdown plus complexes', 'Moins adapté forex/CFD'],
    sources: [
      { label: 'Site officiel Topstep', url: 'https://www.topstep.com/' },
      { label: 'Help Center Topstep', url: 'https://help.topstep.com/' },
    ],
  }),
  firm({
    id: 5,
    slug: 'apex-trader-funding',
    name: 'Apex Trader Funding',
    status: 'À surveiller',
    score: 66,
    founded: 2021,
    headquarters: 'États-Unis',
    bestFor: 'traders futures attirés par les fortes promotions',
    verdict: 'Très populaire grâce aux promotions, mais les règles de payout et de cohérence demandent une lecture froide.',
    priceFrom: 37,
    profitSplit: 90,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 3,
    transparencyScore: 13,
    payoutProof: true,
    logoDomain: 'apextraderfunding.com',
    communitySignal: 'Volume énorme de retours, positifs et négatifs : vérifier les règles avant paiement.',
    styles: ['Futures', 'Scalping', 'Intraday'],
    reviewSignals: {
      redditScore: 48,
      redditMentions: 'nombreux retours Reddit sur payouts, cohérence, trailing threshold et règles de retrait',
      redditSignal: 'Négatif',
      trustpilotReliabilityScore: 45,
      trustpilotReliability: 'Faible',
      trustpilotNote: 'Les avis très positifs doivent être fortement pondérés par les retours Reddit et les règles de payout.',
      payoutRiskScore: 78,
      payoutRisk: 'Élevé',
      payoutIssues: [
        'Règles de cohérence et de payout souvent citées comme source de frustration.',
        'Trailing threshold difficile à gérer pour les débutants.',
        'Promotions fréquentes pouvant masquer le coût réel et les contraintes.',
      ],
      lastSignalCheck: REVIEW_DATE,
    },
    products: [
      product({
        id: 'apex-evaluation',
        name: 'Evaluation Accounts',
        type: 'Futures evaluation',
        description: 'Évaluations futures avec comptes de tailles multiples et promotions fréquentes.',
        accountSizeMin: 25000,
        accountSizeMax: 300000,
        entryFeeMin: 37,
        entryFeeMax: 657,
        maxDailyLoss: 'règles futures spécifiques',
        maxDrawdown: 'trailing threshold',
        profitSplit: 'jusqu’à 90%',
        platforms: ['NinjaTrader', 'Tradovate', 'Rithmic'],
        tradableAssets: ['Futures'],
        consistencyRule: 'Règles de cohérence et payout à lire avant chaque retrait.',
        linkToStart: 'https://apextraderfunding.com/',
        isPopular: true,
      }),
    ],
    strengths: ['Prix promo agressifs', 'Large choix de tailles', 'Très grosse communauté futures'],
    weaknesses: ['Règles de payout sensibles', 'Promotions qui masquent parfois le risque', 'Signal communautaire bruyant'],
    sources: [
      { label: 'Site officiel Apex', url: 'https://apextraderfunding.com/' },
      { label: 'Apex Support', url: 'https://support.apextraderfunding.com/' },
    ],
  }),
  firm({
    id: 6,
    slug: 'trade-the-pool',
    name: 'Trade The Pool',
    status: 'Active',
    score: 76,
    founded: 2022,
    headquarters: 'Israël',
    bestFor: 'traders actions US',
    verdict: 'Positionnement différent : financement orienté actions, utile pour diversifier hors forex/futures.',
    priceFrom: 97,
    profitSplit: 80,
    drawdownType: 'Static',
    newsTrading: 'Variable',
    eaAllowed: 'Non',
    payoutDelay: 'variable',
    incidents: 1,
    transparencyScore: 15,
    payoutProof: true,
    recentRuleChange: false,
    logoDomain: 'tradethepool.com',
    communitySignal: 'Niche plus petite, mais proposition claire sur les actions.',
    styles: ['Actions', 'Intraday', 'Swing'],
    products: [
      product({
        id: 'ttp-stock-trading',
        name: 'Stock Trading Program',
        description: 'Programme pour traders actions avec pouvoir d’achat et règles de perte.',
        accountSizeMin: 20000,
        accountSizeMax: 260000,
        entryFeeMin: 97,
        entryFeeMax: 1240,
        profitSplit: 'jusqu’à 80%',
        platforms: ['Plateforme dédiée'],
        tradableAssets: ['Actions US'],
        linkToStart: 'https://tradethepool.com/',
      }),
    ],
    strengths: ['Niche actions claire', 'Alternative aux CFD', 'Acteur lié à l’écosystème The5ers'],
    weaknesses: ['Moins adapté forex/futures', 'Règles actions spécifiques'],
    sources: [
      { label: 'Site officiel Trade The Pool', url: 'https://tradethepool.com/' },
      { label: 'FAQ Trade The Pool', url: 'https://tradethepool.com/faq/' },
    ],
  }),
  firm({
    id: 7,
    slug: 'e8-markets',
    name: 'E8 Markets',
    status: 'Active',
    score: 75,
    founded: 2021,
    headquarters: 'États-Unis',
    bestFor: 'traders CFD qui veulent une interface moderne',
    verdict: 'Marque bien présentée et populaire, avec un discours clair sur la simulation et les payouts discrétionnaires.',
    priceFrom: 48,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 2,
    transparencyScore: 14,
    payoutProof: true,
    logoDomain: 'e8markets.com',
    communitySignal: 'Bonne traction marketing, signal à compléter par vérification des règles exactes.',
    styles: ['Forex', 'Futures', 'Crypto'],
    products: [
      product({
        id: 'e8-account',
        name: 'E8 Challenge',
        description: 'Programme d’évaluation sur capital simulé avec forex, futures et crypto.',
        accountSizeMin: 5000,
        accountSizeMax: 500000,
        entryFeeMin: 48,
        entryFeeMax: 988,
        profitSplit: 'jusqu’à 80%+',
        platforms: ['TradeLocker', 'cTrader', 'Match-Trader'],
        tradableAssets: ['Forex', 'Futures', 'Crypto'],
        linkToStart: 'https://e8markets.com/',
      }),
    ],
    strengths: ['Expérience produit moderne', 'Positionnement simulation explicite', 'Payouts publics revendiqués'],
    weaknesses: ['Règles variables', 'Historique plus court que FTMO/Topstep'],
    sources: [
      { label: 'Site officiel E8 Markets', url: 'https://e8markets.com/' },
      { label: 'Help Center E8', url: 'https://help.e8markets.com/' },
    ],
  }),
  firm({
    id: 8,
    slug: 'funding-pips',
    name: 'Funding Pips',
    status: 'À surveiller',
    score: 70,
    founded: 2022,
    headquarters: 'Émirats arabes unis',
    bestFor: 'traders cherchant des challenges CFD très accessibles',
    verdict: 'Très visible et compétitif, mais le profil récent impose de suivre les règles, partenaires brokers et retours payout.',
    priceFrom: 20,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 2,
    transparencyScore: 13,
    payoutProof: true,
    logoDomain: 'fundingpips.com',
    communitySignal: 'Très discuté, avec un besoin de tri entre promotions et retours réels.',
    products: [
      product({
        id: 'fundingpips-evaluation',
        name: 'Evaluation',
        description: 'Challenge CFD avec plusieurs tailles de compte et prix d’appel bas.',
        accountSizeMin: 5000,
        accountSizeMax: 100000,
        entryFeeMin: 20,
        entryFeeMax: 499,
        profitSplit: 'jusqu’à 100% selon offres',
        platforms: ['cTrader', 'Match-Trader', 'DXtrade'],
        tradableAssets: ['Forex', 'Indices', 'Métaux', 'Crypto'],
        linkToStart: 'https://fundingpips.com/',
      }),
    ],
    strengths: ['Prix bas', 'Marketing fort', 'Payouts revendiqués publiquement'],
    weaknesses: ['Historique court', 'Dépendance aux règles actuelles de plateforme', 'Besoin de vérification avant achat'],
    sources: [
      { label: 'Site officiel Funding Pips', url: 'https://fundingpips.com/' },
      { label: 'Help Center Funding Pips', url: 'https://help.fundingpips.com/' },
    ],
  }),
  firm({
    id: 9,
    slug: 'maven-trading',
    name: 'Maven Trading',
    status: 'Active',
    score: 73,
    founded: 2022,
    headquarters: 'Canada',
    bestFor: 'traders CFD qui veulent des challenges accessibles',
    verdict: 'Acteur récent mais visible, intéressant si les règles du programme choisi collent à ton style.',
    priceFrom: 14,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: '10 jours ouvrés sur certains programmes',
    incidents: 1,
    transparencyScore: 14,
    payoutProof: true,
    recentRuleChange: false,
    logoDomain: 'maventrading.com',
    communitySignal: 'Signal communautaire en croissance, encore moins profond que les grandes marques.',
    products: [
      product({
        id: 'maven-challenge',
        name: 'Maven Challenge',
        description: 'Évaluations 1-step, 2-step et 3-step avec petites tailles très accessibles.',
        accountSizeMin: 2000,
        accountSizeMax: 200000,
        entryFeeMin: 14,
        entryFeeMax: 800,
        profitTarget: '8% / 5% selon modèle',
        maxDailyLoss: '2% à 4% selon modèle',
        maxDrawdown: '3% à 8% selon modèle',
        profitSplit: '80%',
        platforms: ['MT5'],
        tradableAssets: ['Forex', 'Indices', 'Métaux', 'Crypto'],
        hasConsistencyRule: false,
        consistencyRule: undefined,
        linkToStart: 'https://maventrading.com/',
      }),
    ],
    strengths: ['Prix d’entrée très bas', 'Offres lisibles sur le site', 'Pas de cohérence sur certains modèles'],
    weaknesses: ['Historique récent', 'Montants faibles utiles surtout pour tester'],
    sources: [
      { label: 'Site officiel Maven Trading', url: 'https://maventrading.com/' },
      { label: 'FAQ Maven Trading', url: 'https://help.maventrading.com/' },
    ],
  }),
  firm({
    id: 10,
    slug: 'alpha-capital-group',
    name: 'Alpha Capital Group',
    status: 'Active',
    score: 78,
    founded: 2021,
    headquarters: 'Royaume-Uni',
    bestFor: 'traders forex qui veulent une marque UK visible',
    verdict: 'Acteur sérieux à surveiller favorablement, avec une offre structurée et une marque assez installée.',
    priceFrom: 97,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 1,
    transparencyScore: 15,
    payoutProof: true,
    logoDomain: 'alphacapitalgroup.uk',
    communitySignal: 'Bonne notoriété dans le segment forex prop firm.',
    products: [
      product({
        id: 'alpha-evaluation',
        name: 'Alpha Pro Evaluation',
        description: 'Évaluation forex/CFD avec tailles de compte jusqu’à 200K simulés.',
        accountSizeMax: 200000,
        entryFeeMin: 97,
        profitSplit: 'jusqu’à 80%+',
        platforms: ['MT5'],
        tradableAssets: ['Forex', 'Indices', 'Métaux'],
        linkToStart: 'https://alphacapitalgroup.uk/',
      }),
    ],
    sources: [
      { label: 'Site officiel Alpha Capital Group', url: 'https://alphacapitalgroup.uk/' },
    ],
  }),
  firm({
    id: 11,
    slug: 'fxify',
    name: 'FXIFY',
    status: 'Active',
    score: 74,
    founded: 2023,
    headquarters: 'Royaume-Uni / International',
    bestFor: 'traders qui veulent beaucoup de programmes et d’assets',
    verdict: 'Offre large, très marketing, avec broker backing revendiqué ; bon candidat mais règles à filtrer par programme.',
    priceFrom: 0,
    profitSplit: 90,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Oui',
    payoutDelay: 'variable',
    incidents: 2,
    transparencyScore: 14,
    payoutProof: true,
    logoDomain: 'fxify.com',
    communitySignal: 'Forte présence marketing, beaucoup de programmes et de promotions.',
    products: [
      product({
        id: 'fxify-programs',
        name: 'FXIFY Programs',
        description: 'Programmes one phase, two phase, three phase, instant funding et crypto.',
        accountSizeMax: 400000,
        profitSplit: 'jusqu’à 90%',
        platforms: ['MT4', 'MT5'],
        tradableAssets: ['Forex', 'Indices', 'Actions CFD', 'Crypto'],
        linkToStart: 'https://fxify.com/',
      }),
    ],
    strengths: ['Large choix de programmes', 'EAs autorisés selon présentation', 'Beaucoup d’actifs'],
    weaknesses: ['Promotions nombreuses', 'Prix et règles à vérifier modèle par modèle'],
    sources: [{ label: 'Site officiel FXIFY', url: 'https://fxify.com/' }],
  }),
  firm({
    id: 12,
    slug: 'aqua-funded',
    name: 'AquaFunded',
    status: 'À surveiller',
    score: 69,
    founded: 2023,
    headquarters: 'International',
    bestFor: 'traders attirés par instant funding et splits élevés',
    verdict: 'Offre agressive et très orientée marketing ; intéressante seulement avec lecture complète des règles.',
    priceFrom: 35,
    profitSplit: 100,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 2,
    transparencyScore: 12,
    payoutProof: true,
    logoDomain: 'aquafunded.com',
    communitySignal: 'Jeune marque très visible, à traiter avec prudence avant achat.',
    products: [
      product({
        id: 'aqua-instant',
        name: 'Instant Funding / Challenges',
        type: 'Instant funding',
        description: 'Produits avec accès rapide et splits élevés selon conditions.',
        accountSizeMax: 200000,
        entryFeeMin: 35,
        profitSplit: 'jusqu’à 100% selon offre',
        platforms: ['MT5', 'cTrader'],
        tradableAssets: ['Forex', 'Indices', 'Crypto'],
        linkToStart: 'https://www.aquafunded.com/',
      }),
    ],
    sources: [{ label: 'Site officiel AquaFunded', url: 'https://www.aquafunded.com/' }],
  }),
  firm({
    id: 13,
    slug: 'goat-funded-trader',
    name: 'GOAT Funded Trader',
    status: 'À surveiller',
    score: 68,
    founded: 2023,
    headquarters: 'International',
    bestFor: 'traders CFD sensibles aux prix promotionnels',
    verdict: 'Marque très visible, mais score plafonné tant que l’historique et les retours payout restent moins établis.',
    priceFrom: 35,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 2,
    logoDomain: 'goatfundedtrader.com',
    communitySignal: 'Beaucoup de visibilité sociale ; diligence nécessaire.',
    products: [
      product({
        id: 'goat-challenges',
        name: 'GOAT Challenges',
        description: 'Challenges CFD avec tailles de compte multiples.',
        accountSizeMax: 200000,
        entryFeeMin: 35,
        profitSplit: 'jusqu’à 90%',
        platforms: ['MT5'],
        tradableAssets: ['Forex', 'Indices', 'Métaux', 'Crypto'],
        linkToStart: 'https://www.goatfundedtrader.com/',
      }),
    ],
    sources: [{ label: 'Site officiel GOAT Funded Trader', url: 'https://www.goatfundedtrader.com/' }],
  }),
  firm({
    id: 14,
    slug: 'brightfunded',
    name: 'BrightFunded',
    status: 'Active',
    score: 73,
    founded: 2023,
    headquarters: 'Pays-Bas / International',
    bestFor: 'traders CFD qui veulent un site clair et payouts rapides annoncés',
    verdict: 'Acteur récent mais proprement présenté ; intéressant, avec prudence sur les promesses de rapidité.',
    priceFrom: 49,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: '24h annoncé sur certains cas',
    incidents: 1,
    transparencyScore: 14,
    payoutProof: true,
    logoDomain: 'brightfunded.com',
    communitySignal: 'Positionnement transparent sur plateformes et payouts, mais historique encore jeune.',
    products: [
      product({
        id: 'brightfunded-evaluation',
        name: 'BrightFunded Evaluation',
        description: 'Évaluation jusqu’à 400K avec cTrader, MT5 et DXtrade.',
        accountSizeMax: 400000,
        entryFeeMin: 49,
        profitSplit: 'jusqu’à 100% selon scaling',
        platforms: ['cTrader', 'MT5', 'DXtrade'],
        tradableAssets: ['Forex', 'Indices', 'Matières premières'],
        hasConsistencyRule: false,
        consistencyRule: undefined,
        linkToStart: 'https://brightfunded.com/',
      }),
    ],
    sources: [{ label: 'Site officiel BrightFunded', url: 'https://brightfunded.com/' }],
  }),
  firm({
    id: 15,
    slug: 'instant-funding',
    name: 'Instant Funding',
    status: 'Active',
    score: 76,
    founded: 2021,
    headquarters: 'Royaume-Uni',
    bestFor: 'traders qui veulent éviter une évaluation classique',
    verdict: 'Offre instant funding plus mature que beaucoup de concurrents, mais les règles de drawdown intelligent doivent être comprises.',
    priceFrom: 39,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: '14 jours puis hebdomadaire sur certains comptes',
    incidents: 1,
    transparencyScore: 15,
    payoutProof: true,
    logoDomain: 'instantfunding.com',
    communitySignal: 'Marque installée dans la niche instant funding.',
    products: [
      product({
        id: 'instant-funding-account',
        name: 'Instant Funding Account',
        type: 'Instant funding',
        description: 'Accès direct à un compte simulé avec règles de smart drawdown et scaling.',
        accountSizeMin: 625,
        accountSizeMax: 300000,
        entryFeeMin: 39,
        profitTarget: 'pas d’objectif fixe sur certains comptes',
        maxDailyLoss: 'aucune limite quotidienne sur certains comptes',
        maxDrawdown: '10% puis smart drawdown',
        profitSplit: '80% à 90%',
        platforms: ['MT5', 'cTrader', 'Match-Trader'],
        tradableAssets: ['Forex', 'Indices', 'Crypto'],
        hasConsistencyRule: false,
        consistencyRule: undefined,
        linkToStart: 'https://instantfunding.com/',
      }),
    ],
    sources: [{ label: 'Site officiel Instant Funding', url: 'https://instantfunding.com/' }],
  }),
  firm({
    id: 16,
    slug: 'funded-trading-plus',
    name: 'Funded Trading Plus',
    status: 'Active',
    score: 74,
    founded: 2021,
    headquarters: 'Royaume-Uni',
    bestFor: 'traders CFD qui veulent plusieurs formats de challenge',
    verdict: 'Acteur plutôt établi dans les prop firms CFD, avec règles à vérifier selon le type de compte choisi.',
    priceFrom: 119,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 1,
    transparencyScore: 14,
    payoutProof: true,
    logoDomain: 'fundedtradingplus.com',
    communitySignal: 'Bon historique relatif, sans atteindre les leaders historiques.',
    products: [
      product({
        id: 'ftp-programs',
        name: 'Funded Trading Plus Programs',
        description: 'Programmes d’évaluation et instant funding selon profils.',
        accountSizeMax: 200000,
        entryFeeMin: 119,
        profitSplit: 'jusqu’à 90%',
        platforms: ['MT4', 'MT5', 'cTrader'],
        tradableAssets: ['Forex', 'Indices', 'Métaux', 'Crypto'],
        linkToStart: 'https://www.fundedtradingplus.com/',
      }),
    ],
    sources: [{ label: 'Site officiel Funded Trading Plus', url: 'https://www.fundedtradingplus.com/' }],
  }),
  firm({
    id: 17,
    slug: 'blue-guardian',
    name: 'Blue Guardian',
    status: 'À surveiller',
    score: 70,
    founded: 2019,
    headquarters: 'Royaume-Uni / International',
    bestFor: 'traders cherchant une alternative CFD avec instant funding',
    verdict: 'Offre visible et installée, mais le score reste prudent sur les règles et l’évolution commerciale.',
    priceFrom: 47,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 2,
    logoDomain: 'blueguardian.com',
    communitySignal: 'Présence communautaire correcte, signal à confirmer par preuves payout récentes.',
    products: [
      product({
        id: 'blueguardian-programs',
        name: 'Blue Guardian Programs',
        description: 'Challenges et offres instant funding selon profil.',
        accountSizeMax: 200000,
        entryFeeMin: 47,
        profitSplit: 'jusqu’à 90%',
        platforms: ['MT5'],
        tradableAssets: ['Forex', 'Indices', 'Métaux', 'Crypto'],
        linkToStart: 'https://blueguardian.com/',
      }),
    ],
    sources: [{ label: 'Site officiel Blue Guardian', url: 'https://blueguardian.com/' }],
  }),
  firm({
    id: 18,
    slug: 'fintokei',
    name: 'Fintokei',
    status: 'Active',
    score: 77,
    founded: 2022,
    headquarters: 'Europe / Japon',
    bestFor: 'traders européens ou asiatiques qui veulent une marque plus régulée en apparence',
    verdict: 'Positionnement plus sobre que la moyenne, intéressant pour les traders qui veulent éviter les promesses trop agressives.',
    priceFrom: 79,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 1,
    transparencyScore: 15,
    payoutProof: true,
    recentRuleChange: false,
    logoDomain: 'fintokei.com',
    communitySignal: 'Signal plus institutionnel, moins bruyant que les prop firms très promotionnelles.',
    products: [
      product({
        id: 'fintokei-challenges',
        name: 'Fintokei Programs',
        description: 'Programmes d’évaluation et comptes simulés pour traders forex/CFD.',
        accountSizeMax: 400000,
        entryFeeMin: 79,
        profitSplit: 'jusqu’à 95% selon programme',
        platforms: ['MT4', 'MT5'],
        tradableAssets: ['Forex', 'Indices', 'Métaux'],
        linkToStart: 'https://www.fintokei.com/',
      }),
    ],
    sources: [{ label: 'Site officiel Fintokei', url: 'https://www.fintokei.com/' }],
  }),
  firm({
    id: 19,
    slug: 'audacity-capital',
    name: 'Audacity Capital',
    status: 'Active',
    score: 79,
    founded: 2012,
    headquarters: 'Royaume-Uni',
    bestFor: 'traders qui veulent un acteur ancien basé à Londres',
    verdict: 'Acteur ancien, plus traditionnel, moins orienté promos agressives que beaucoup de nouvelles prop firms.',
    priceFrom: 99,
    profitSplit: 50,
    drawdownType: 'Static',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 1,
    transparencyScore: 16,
    payoutProof: true,
    recentRuleChange: false,
    logoDomain: 'audacity.capital',
    communitySignal: 'Moins viral, mais historique long dans le secteur.',
    products: [
      product({
        id: 'audacity-programs',
        name: 'Funded Trader Programs',
        description: 'Programmes de financement forex avec approche plus traditionnelle.',
        accountSizeMax: 500000,
        entryFeeMin: 99,
        profitSplit: '50% à 80% selon programme',
        platforms: ['MT4', 'MT5'],
        tradableAssets: ['Forex', 'Indices', 'Métaux'],
        linkToStart: 'https://audacity.capital/',
      }),
    ],
    sources: [{ label: 'Site officiel Audacity Capital', url: 'https://audacity.capital/' }],
  }),
  firm({
    id: 20,
    slug: 'city-traders-imperium',
    name: 'City Traders Imperium',
    status: 'Active',
    score: 74,
    founded: 2018,
    headquarters: 'Royaume-Uni',
    bestFor: 'traders forex orientés formation et swing',
    verdict: 'Acteur connu du segment forex, intéressant mais à vérifier car les programmes changent régulièrement.',
    priceFrom: 99,
    profitSplit: 80,
    drawdownType: 'Static',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 1,
    logoDomain: 'citytradersimperium.com',
    communitySignal: 'Nom installé, avec une audience plus formation/trading que pur discount.',
    products: [
      product({
        id: 'cti-programs',
        name: 'CTI Programs',
        description: 'Programmes de challenge et funded accounts forex.',
        accountSizeMax: 200000,
        entryFeeMin: 99,
        profitSplit: 'jusqu’à 100% selon conditions',
        platforms: ['MT5'],
        tradableAssets: ['Forex', 'Indices', 'Métaux'],
        linkToStart: 'https://www.citytradersimperium.com/',
      }),
    ],
    sources: [{ label: 'Site officiel City Traders Imperium', url: 'https://www.citytradersimperium.com/' }],
  }),
  firm({
    id: 21,
    slug: 'pipfarm',
    name: 'PipFarm',
    status: 'À surveiller',
    score: 72,
    founded: 2023,
    headquarters: 'International',
    bestFor: 'traders CFD qui veulent une offre moderne et simple',
    verdict: 'Jeune marque avec une proposition propre ; score prudent faute de long historique public.',
    priceFrom: 49,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 1,
    logoDomain: 'pipfarm.com',
    communitySignal: 'Signal émergent, à renforcer avec preuves de payouts récentes.',
    products: [
      product({
        id: 'pipfarm-programs',
        name: 'PipFarm Programs',
        description: 'Programmes d’évaluation pour forex/CFD.',
        accountSizeMax: 300000,
        entryFeeMin: 49,
        profitSplit: 'variable',
        platforms: ['cTrader'],
        tradableAssets: ['Forex', 'Indices', 'Métaux'],
        linkToStart: 'https://pipfarm.com/',
      }),
    ],
    sources: [{ label: 'Site officiel PipFarm', url: 'https://pipfarm.com/' }],
  }),
  firm({
    id: 22,
    slug: 'lark-funding',
    name: 'Lark Funding',
    status: 'À surveiller',
    score: 68,
    founded: 2022,
    headquarters: 'International',
    bestFor: 'traders qui veulent comparer des offres CFD récentes',
    verdict: 'À garder dans le radar, mais pas dans les recommandations fortes sans revue plus profonde des payouts et règles.',
    priceFrom: 49,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 2,
    logoDomain: 'larkfunding.com',
    communitySignal: 'Signal public plus limité ; prudence.',
    products: [
      product({
        id: 'lark-programs',
        name: 'Lark Funding Programs',
        description: 'Programmes d’évaluation forex/CFD.',
        accountSizeMax: 200000,
        entryFeeMin: 49,
        profitSplit: 'variable',
        platforms: ['MT4', 'MT5'],
        tradableAssets: ['Forex', 'Indices', 'Métaux'],
        linkToStart: 'https://larkfunding.com/',
      }),
    ],
    sources: [{ label: 'Site officiel Lark Funding', url: 'https://larkfunding.com/' }],
  }),
  firm({
    id: 23,
    slug: 'bespoke-funding-program',
    name: 'Bespoke Funding Program',
    status: 'À surveiller',
    score: 61,
    founded: 2022,
    headquarters: 'International',
    bestFor: 'traders qui font une veille large du marché',
    verdict: 'À considérer comme entrée de radar plus que comme recommandation, tant que les signaux récents ne sont pas solidement confirmés.',
    priceFrom: 0,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 3,
    legalVerified: false,
    transparencyScore: 9,
    logoDomain: 'bespokefundingprogram.com',
    communitySignal: 'Signal communautaire insuffisant pour une recommandation forte.',
    products: [
      product({
        id: 'bespoke-programs',
        name: 'Bespoke Programs',
        description: 'Programmes d’évaluation historiques à revérifier avant tout achat.',
        accountSizeMax: 500000,
        profitSplit: 'variable',
        linkToStart: 'https://bespokefundingprogram.com/',
      }),
    ],
    strengths: ['Nom connu par les comparateurs historiques'],
    weaknesses: ['Statut opérationnel et conditions à revérifier fortement', 'Pas de recommandation forte'],
    sources: [{ label: 'Site Bespoke Funding Program', url: 'https://bespokefundingprogram.com/' }],
  }),
  firm({
    id: 24,
    slug: 'tradeify',
    name: 'Tradeify',
    status: 'Active',
    score: 72,
    founded: 2023,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui veulent une alternative moderne',
    verdict: 'Alternative futures en croissance, à comparer avec Topstep, Apex et Take Profit Trader.',
    priceFrom: 99,
    profitSplit: 90,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'quotidien annoncé sur certains plans',
    incidents: 1,
    payoutProof: true,
    logoDomain: 'tradeify.co',
    communitySignal: 'Jeune acteur futures, popularité en hausse.',
    styles: ['Futures', 'Intraday', 'Scalping'],
    products: [
      product({
        id: 'tradeify-futures',
        name: 'Futures Plans',
        type: 'Futures evaluation',
        description: 'Plans futures avec évaluations et offres instant funding.',
        accountSizeMax: 150000,
        entryFeeMin: 99,
        maxDrawdown: 'trailing selon plan',
        profitSplit: 'jusqu’à 90%',
        platforms: ['Tradovate', 'NinjaTrader'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://tradeify.co/',
      }),
    ],
    sources: [{ label: 'Site officiel Tradeify', url: 'https://tradeify.co/' }],
  }),
  firm({
    id: 25,
    slug: 'take-profit-trader',
    name: 'Take Profit Trader',
    status: 'Active',
    score: 73,
    founded: 2021,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui veulent des payouts rapides',
    verdict: 'Offre futures centrée sur la rapidité de passage en PRO et de retrait, à vérifier côté règles de buffer.',
    priceFrom: 99,
    profitSplit: 80,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'day-one annoncé en PRO',
    incidents: 1,
    payoutProof: true,
    logoDomain: 'takeprofittrader.com',
    communitySignal: 'Bonne visibilité dans la niche futures, avec proposition de payout claire.',
    styles: ['Futures', 'Intraday'],
    products: [
      product({
        id: 'tpt-test',
        name: 'TPT Test / PRO',
        type: 'Futures evaluation',
        description: 'Évaluation futures avec passage vers PRO et split 80/20 à 90/10 selon compte.',
        accountSizeMax: 150000,
        entryFeeMin: 99,
        maxDrawdown: 'trailing ou EOD selon PRO+',
        profitSplit: '80% à 90%',
        platforms: ['NinjaTrader', 'Tradovate', 'TradingView', 'Quantower'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://takeprofittrader.com/',
      }),
    ],
    sources: [{ label: 'Site officiel Take Profit Trader', url: 'https://takeprofittrader.com/' }],
  }),
  firm({
    id: 26,
    slug: 'earn2trade',
    name: 'Earn2Trade',
    status: 'Active',
    score: 78,
    founded: 2017,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui veulent un parcours éducatif',
    verdict: 'Acteur futures plus ancien et orienté formation, intéressant pour les traders qui veulent un cadre d’apprentissage.',
    priceFrom: 150,
    profitSplit: 80,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable via partenaires',
    incidents: 1,
    transparencyScore: 16,
    payoutProof: true,
    recentRuleChange: false,
    logoDomain: 'earn2trade.com',
    communitySignal: 'Réputation plus ancienne que beaucoup de programmes futures récents.',
    styles: ['Futures', 'Formation'],
    products: [
      product({
        id: 'earn2trade-gauntlet',
        name: 'Gauntlet / Trader Career Path',
        type: 'Futures evaluation',
        description: 'Parcours d’évaluation futures avec composante éducative.',
        accountSizeMax: 200000,
        entryFeeMin: 150,
        maxDrawdown: 'règles futures spécifiques',
        profitSplit: 'jusqu’à 80%',
        platforms: ['NinjaTrader', 'Finamark', 'Rithmic'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://www.earn2trade.com/',
      }),
    ],
    sources: [{ label: 'Site officiel Earn2Trade', url: 'https://www.earn2trade.com/' }],
  }),
  firm({
    id: 27,
    slug: 'oneup-trader',
    name: 'OneUp Trader',
    status: 'Active',
    score: 72,
    founded: 2017,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui veulent une évaluation classique',
    verdict: 'Acteur futures installé, moins flashy que les nouveaux venus mais à comparer sur coût total et règles.',
    priceFrom: 125,
    profitSplit: 80,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 1,
    payoutProof: true,
    recentRuleChange: false,
    logoDomain: 'oneuptrader.com',
    communitySignal: 'Présence durable sur la niche futures.',
    styles: ['Futures'],
    products: [
      product({
        id: 'oneup-evaluation',
        name: 'OneUp Evaluation',
        type: 'Futures evaluation',
        description: 'Évaluation futures avec comptes de tailles multiples.',
        accountSizeMax: 250000,
        entryFeeMin: 125,
        maxDrawdown: 'trailing',
        profitSplit: 'jusqu’à 80%',
        platforms: ['NinjaTrader', 'Rithmic'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://www.oneuptrader.com/',
      }),
    ],
    sources: [{ label: 'Site officiel OneUp Trader', url: 'https://www.oneuptrader.com/' }],
  }),
  firm({
    id: 28,
    slug: 'elite-trader-funding',
    name: 'Elite Trader Funding',
    status: 'À surveiller',
    score: 64,
    founded: 2021,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui comparent les promotions',
    verdict: 'Acteur futures connu pour ses offres, mais score prudent à cause de la complexité des règles et du bruit communautaire.',
    priceFrom: 45,
    profitSplit: 90,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 3,
    logoDomain: 'elitetraderfunding.app',
    communitySignal: 'Avis très mélangés ; lire les règles et retours récents.',
    styles: ['Futures'],
    products: [
      product({
        id: 'elite-futures',
        name: 'Elite Evaluations',
        type: 'Futures evaluation',
        description: 'Évaluations futures avec promotions fréquentes.',
        accountSizeMax: 300000,
        entryFeeMin: 45,
        maxDrawdown: 'trailing selon plan',
        profitSplit: 'jusqu’à 90%',
        platforms: ['NinjaTrader', 'Rithmic'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://elitetraderfunding.app/',
      }),
    ],
    sources: [{ label: 'Site officiel Elite Trader Funding', url: 'https://elitetraderfunding.app/' }],
  }),
  firm({
    id: 29,
    slug: 'tickticktrader',
    name: 'TickTickTrader',
    status: 'À surveiller',
    score: 68,
    founded: 2022,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui veulent des comptes simples',
    verdict: 'Nom actif de la niche futures, mais à garder en surveillance faute de profondeur historique comparable à Topstep.',
    priceFrom: 99,
    profitSplit: 80,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 2,
    logoDomain: 'tickticktrader.com',
    communitySignal: 'Signal public correct mais encore à consolider.',
    styles: ['Futures'],
    products: [
      product({
        id: 'ticktick-futures',
        name: 'TickTickTrader Accounts',
        type: 'Futures evaluation',
        description: 'Évaluations futures avec tailles de compte multiples.',
        accountSizeMax: 250000,
        entryFeeMin: 99,
        maxDrawdown: 'trailing',
        profitSplit: 'variable',
        platforms: ['NinjaTrader', 'Rithmic'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://tickticktrader.com/',
      }),
    ],
    sources: [{ label: 'Site officiel TickTickTrader', url: 'https://tickticktrader.com/' }],
  }),
  firm({
    id: 30,
    slug: 'leeloo-trading',
    name: 'Leeloo Trading',
    status: 'Active',
    score: 70,
    founded: 2020,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui veulent des évaluations classiques',
    verdict: 'Acteur futures connu, à comparer sur drawdown, resets, activation et règles de payout.',
    priceFrom: 77,
    profitSplit: 80,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 2,
    logoDomain: 'leelootrading.com',
    communitySignal: 'Nom connu mais avis contrastés selon promotions et règles.',
    styles: ['Futures'],
    products: [
      product({
        id: 'leeloo-accounts',
        name: 'Leeloo Evaluation',
        type: 'Futures evaluation',
        description: 'Évaluations futures avec différentes tailles et options.',
        accountSizeMax: 300000,
        entryFeeMin: 77,
        maxDrawdown: 'trailing',
        profitSplit: 'variable',
        platforms: ['NinjaTrader', 'Rithmic'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://www.leelootrading.com/',
      }),
    ],
    sources: [{ label: 'Site officiel Leeloo Trading', url: 'https://www.leelootrading.com/' }],
  }),
  firm({
    id: 31,
    slug: 'uprofit-trader',
    name: 'UProfit Trader',
    status: 'Active',
    score: 69,
    founded: 2019,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui veulent une alternative aux gros noms',
    verdict: 'Acteur futures actif, à classer en alternative plutôt qu’en choix prioritaire sans revue poussée.',
    priceFrom: 89,
    profitSplit: 80,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 2,
    logoDomain: 'uprofittrader.com',
    communitySignal: 'Présence stable, mais retours moins massifs que Topstep/Apex.',
    styles: ['Futures'],
    products: [
      product({
        id: 'uprofit-accounts',
        name: 'UProfit Evaluations',
        type: 'Futures evaluation',
        description: 'Évaluations futures avec comptes de tailles multiples.',
        accountSizeMax: 200000,
        entryFeeMin: 89,
        maxDrawdown: 'trailing',
        profitSplit: 'variable',
        platforms: ['NinjaTrader', 'Rithmic'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://uprofittrader.com/',
      }),
    ],
    sources: [{ label: 'Site officiel UProfit Trader', url: 'https://uprofittrader.com/' }],
  }),
  firm({
    id: 32,
    slug: 'myfundedfutures',
    name: 'MyFundedFutures',
    status: 'Active',
    score: 73,
    founded: 2023,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui veulent une alternative récente',
    verdict: 'Acteur récent mais très visible sur futures ; à suivre de près pour règles de payout et stabilité.',
    priceFrom: 80,
    profitSplit: 90,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 1,
    payoutProof: true,
    logoDomain: 'myfundedfutures.com',
    communitySignal: 'Signal récent et en croissance.',
    styles: ['Futures'],
    products: [
      product({
        id: 'mffu-futures',
        name: 'MyFundedFutures Accounts',
        type: 'Futures evaluation',
        description: 'Évaluations futures avec tailles et règles propres.',
        accountSizeMax: 150000,
        entryFeeMin: 80,
        maxDrawdown: 'trailing',
        profitSplit: 'jusqu’à 90%',
        platforms: ['NinjaTrader', 'Tradovate'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://myfundedfutures.com/',
      }),
    ],
    sources: [{ label: 'Site officiel MyFundedFutures', url: 'https://myfundedfutures.com/' }],
  }),
  firm({
    id: 33,
    slug: 'bulenox',
    name: 'Bulenox',
    status: 'À surveiller',
    score: 65,
    founded: 2020,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui surveillent les alternatives low cost',
    verdict: 'Acteur futures connu mais à mettre en surveillance sur règles, activation, drawdown et retours payout.',
    priceFrom: 78,
    profitSplit: 80,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 3,
    logoDomain: 'bulenox.com',
    communitySignal: 'Avis contrastés ; diligence renforcée.',
    styles: ['Futures'],
    products: [
      product({
        id: 'bulenox-evaluation',
        name: 'Bulenox Evaluation',
        type: 'Futures evaluation',
        description: 'Évaluations futures avec comptes de tailles multiples.',
        accountSizeMax: 250000,
        entryFeeMin: 78,
        maxDrawdown: 'trailing',
        profitSplit: 'variable',
        platforms: ['NinjaTrader', 'Rithmic'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://bulenox.com/',
      }),
    ],
    sources: [{ label: 'Site officiel Bulenox', url: 'https://bulenox.com/' }],
  }),
  firm({
    id: 34,
    slug: 'fast-track-trading',
    name: 'Fast Track Trading',
    status: 'À surveiller',
    score: 60,
    founded: 2024,
    headquarters: 'États-Unis',
    bestFor: 'traders futures qui étudient les nouveaux modèles',
    verdict: 'À surveiller seulement : marque récente, promesse rapide, historique encore insuffisant pour recommander fort.',
    priceFrom: 0,
    profitSplit: 90,
    drawdownType: 'Trailing',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'variable',
    incidents: 3,
    transparencyScore: 9,
    logoDomain: 'fasttracktrading.net',
    communitySignal: 'Trop récent pour une confiance forte.',
    styles: ['Futures'],
    products: [
      product({
        id: 'fasttrack-futures',
        name: 'Fast Track Futures',
        type: 'Futures evaluation',
        description: 'Offre futures récente à contrôler avant achat.',
        accountSizeMax: 150000,
        maxDrawdown: 'variable',
        profitSplit: 'variable',
        platforms: ['À vérifier'],
        tradableAssets: ['Futures'],
        linkToStart: 'https://fasttracktrading.net/',
      }),
    ],
    strengths: ['Nom à suivre dans la veille marché'],
    weaknesses: ['Historique court', 'Pas assez de recul', 'Ne pas classer comme recommandation prioritaire'],
    sources: [{ label: 'Site Fast Track Trading', url: 'https://fasttracktrading.net/' }],
  }),
  firm({
    id: 35,
    slug: 'the-funded-trader',
    name: 'The Funded Trader',
    status: 'À surveiller',
    score: 35,
    founded: 2021,
    headquarters: 'États-Unis',
    bestFor: 'cas de vigilance sectorielle',
    verdict: 'Ancien nom majeur qui a connu de fortes controverses opérationnelles ; à ne pas traiter comme recommandation sans preuve récente robuste.',
    priceFrom: 0,
    profitSplit: 80,
    drawdownType: 'Hybride',
    newsTrading: 'Variable',
    eaAllowed: 'Variable',
    payoutDelay: 'à revérifier',
    incidents: 5,
    legalVerified: false,
    transparencyScore: 5,
    payoutProof: false,
    logoDomain: 'thefundedtraderprogram.com',
    communitySignal: 'Historique de controverses et de plaintes publiques.',
    reviewSignals: {
      redditScore: 18,
      redditMentions: 'retours négatifs très visibles autour des interruptions, remboursements et payouts',
      redditSignal: 'Négatif',
      trustpilotReliabilityScore: 18,
      trustpilotReliability: 'Faible',
      trustpilotNote: 'Les avis positifs ne suffisent pas à compenser l’historique opérationnel et les alertes communautaires.',
      payoutRiskScore: 94,
      payoutRisk: 'Critique',
      payoutIssues: [
        'Historique public de fortes controverses opérationnelles.',
        'Risque élevé de divergence entre marketing, avis et expérience réelle des traders.',
        'À exclure des recommandations tant que des preuves récentes et robustes ne sont pas établies.',
      ],
      lastSignalCheck: REVIEW_DATE,
    },
    products: [],
    strengths: ['Nom connu historiquement'],
    weaknesses: ['Risque opérationnel élevé', 'Historique controversé', 'À exclure des recommandations fortes'],
    sources: [{ label: 'Site The Funded Trader', url: 'https://thefundedtraderprogram.com/' }],
  }),
  firm({
    id: 36,
    slug: 'myfundedfx',
    name: 'MyFundedFX / Seacrest Markets',
    status: 'Fermée',
    score: 5,
    founded: 2022,
    headquarters: 'États-Unis / Afrique du Sud',
    bestFor: 'cas d’école à éviter',
    verdict: 'Le domaine redirige vers un message indiquant que Seacrest Markets n’opère plus : aucun achat recommandé.',
    priceFrom: 0,
    profitSplit: 0,
    drawdownType: 'Hybride',
    newsTrading: 'Non recommandé',
    eaAllowed: 'Non',
    payoutDelay: 'non applicable',
    incidents: 6,
    legalVerified: false,
    transparencyScore: 1,
    payoutProof: false,
    logoDomain: 'myfundedfx.com',
    communitySignal: 'Statut fermé confirmé par message public du domaine redirigé.',
    reviewSignals: {
      redditScore: 5,
      redditMentions: 'archives de plaintes et statut fermé',
      redditSignal: 'Négatif',
      trustpilotReliabilityScore: 10,
      trustpilotReliability: 'Faible',
      trustpilotNote: 'Les avis historiques ne sont plus utiles pour un achat : le statut opérationnel prime.',
      payoutRiskScore: 100,
      payoutRisk: 'Critique',
      payoutIssues: [
        'Seacrest Markets indique publiquement ne plus opérer.',
        'Aucun produit actif recommandé.',
        'Risque opérationnel matérialisé : ne pas envoyer de capital ou acheter de challenge.',
      ],
      lastSignalCheck: REVIEW_DATE,
    },
    products: [],
    strengths: ['Aucune pour un achat actuel'],
    weaknesses: ['Fermeture', 'Aucun produit actif recommandé', 'Risque opérationnel matérialisé'],
    sources: [{ label: 'Message de fermeture Seacrest Markets', url: 'https://myfundedfx.com/' }],
  }),
  firm({
    id: 37,
    slug: 'myforexfunds',
    name: 'My Forex Funds',
    status: 'Fermée',
    score: 8,
    founded: 2020,
    headquarters: 'Canada',
    bestFor: 'cas d’école à éviter',
    verdict: 'Exemple majeur de risque sectoriel : popularité élevée ne signifie pas sécurité opérationnelle.',
    priceFrom: 0,
    profitSplit: 0,
    drawdownType: 'Hybride',
    newsTrading: 'Non recommandé',
    eaAllowed: 'Non',
    payoutDelay: 'non applicable',
    incidents: 6,
    legalVerified: false,
    transparencyScore: 2,
    payoutProof: false,
    logoDomain: 'myforexfunds.com',
    communitySignal: 'Nom très connu, mais non exploitable comme option d’achat.',
    reviewSignals: {
      redditScore: 8,
      redditMentions: 'archives de crise, plaintes traders et action réglementaire',
      redditSignal: 'Négatif',
      trustpilotReliabilityScore: 12,
      trustpilotReliability: 'Faible',
      trustpilotNote: 'La note d’avis historique n’a plus de valeur de confiance depuis l’action réglementaire.',
      payoutRiskScore: 100,
      payoutRisk: 'Critique',
      payoutIssues: [
        'Action réglementaire publique contre l’opérateur.',
        'Activité non exploitable comme option d’achat actuelle.',
        'Cas d’école montrant que popularité et avis publics ne garantissent pas la sécurité.',
      ],
      lastSignalCheck: REVIEW_DATE,
    },
    products: [],
    strengths: ['Aucune pour un achat actuel'],
    weaknesses: ['Fermeture', 'Risque réglementaire matérialisé', 'Aucun produit à recommander'],
    sources: [{ label: 'CFTC - My Forex Funds', url: 'https://www.cftc.gov/' }],
  }),
  firm({
    id: 38,
    slug: 'surgetrader',
    name: 'SurgeTrader',
    status: 'Fermée',
    score: 6,
    founded: 2021,
    headquarters: 'États-Unis',
    bestFor: 'cas d’école à éviter',
    verdict: 'Ancien acteur connu dont la fermeture rappelle l’importance de surveiller les statuts opérationnels.',
    priceFrom: 0,
    profitSplit: 0,
    drawdownType: 'Static',
    newsTrading: 'Non recommandé',
    eaAllowed: 'Non',
    payoutDelay: 'non applicable',
    incidents: 5,
    legalVerified: false,
    transparencyScore: 2,
    payoutProof: false,
    logoDomain: 'surgetrader.com',
    communitySignal: 'À conserver dans les archives du radar comme alerte de risque.',
    products: [],
    strengths: ['Aucune pour un achat actuel'],
    weaknesses: ['Fermeture', 'Aucun produit actif', 'Historique à risque'],
    sources: [{ label: 'Ancien site SurgeTrader', url: 'https://surgetrader.com/' }],
  }),
  firm({
    id: 39,
    slug: 'true-forex-funds',
    name: 'True Forex Funds',
    status: 'Fermée',
    score: 7,
    founded: 2021,
    headquarters: 'Hongrie',
    bestFor: 'cas d’école à éviter',
    verdict: 'Nom historique du secteur désormais à classer comme non recommandable pour achat.',
    priceFrom: 0,
    profitSplit: 0,
    drawdownType: 'Hybride',
    newsTrading: 'Non recommandé',
    eaAllowed: 'Non',
    payoutDelay: 'non applicable',
    incidents: 5,
    legalVerified: false,
    transparencyScore: 2,
    payoutProof: false,
    logoDomain: 'trueforexfunds.com',
    communitySignal: 'Signal historique de fermeture et d’instabilité.',
    products: [],
    strengths: ['Aucune pour un achat actuel'],
    weaknesses: ['Fermeture', 'Risque opérationnel élevé', 'Aucun produit recommandé'],
    sources: [{ label: 'Ancien site True Forex Funds', url: 'https://trueforexfunds.com/' }],
  }),
  firm({
    id: 40,
    slug: 'fidelcrest',
    name: 'Fidelcrest',
    status: 'Fermée',
    score: 9,
    founded: 2018,
    headquarters: 'International',
    bestFor: 'cas d’école à éviter',
    verdict: 'Ancien acteur connu, à garder dans les archives de risque plutôt que dans les recommandations.',
    priceFrom: 0,
    profitSplit: 0,
    drawdownType: 'Hybride',
    newsTrading: 'Non recommandé',
    eaAllowed: 'Non',
    payoutDelay: 'non applicable',
    incidents: 5,
    legalVerified: false,
    transparencyScore: 2,
    payoutProof: false,
    logoDomain: 'fidelcrest.com',
    communitySignal: 'Historique connu, mais non prioritaire pour achat.',
    products: [],
    strengths: ['Aucune pour un achat actuel'],
    weaknesses: ['Statut non recommandable', 'Historique à risque', 'Aucun produit actif à privilégier'],
    sources: [{ label: 'Ancien site Fidelcrest', url: 'https://fidelcrest.com/' }],
  }),
];

export const activeFirms = propFirms.filter((firm) => firm.status === 'Active');
export const riskyFirms = propFirms.filter((firm) => firm.status === 'À surveiller');
export const topFirms = [...propFirms]
  .filter((firm) => firm.status !== 'Fermée')
  .sort((a, b) => b.score - a.score);

export function getFirmBySlug(slug: string) {
  return propFirms.find((firm) => firm.slug === slug);
}

export function scoreClass(score: number) {
  if (score >= 80) return 'badge-green';
  if (score >= 60) return 'badge-amber';
  return 'badge-red';
}

export function statusClass(status: PropFirm['status']) {
  if (status === 'Active') return 'badge-green';
  if (status === 'À surveiller') return 'badge-amber';
  return 'badge-red';
}

export function relationshipClass(relationship: PropFirm['commercialRelationship']) {
  return relationship === 'Affiliation transparente' ? 'badge-blue' : 'badge-neutral';
}

export function payoutRiskClass(risk: ReviewSignals['payoutRisk']) {
  if (risk === 'Faible') return 'badge-green';
  if (risk === 'Modéré') return 'badge-amber';
  return 'badge-red';
}

export function reviewReliabilityClass(reliability: ReviewSignals['trustpilotReliability']) {
  if (reliability === 'Forte') return 'badge-green';
  if (reliability === 'Moyenne') return 'badge-amber';
  return 'badge-red';
}

export function formatUsd(value: number) {
  if (value <= 0) return 'À vérifier';
  return new Intl.NumberFormat('fr-FR', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(value);
}
