export type PropFirm = {
  id: number;
  slug: string;
  name: string;
  status: 'Active' | 'Risque' | 'Fermée';
  score: number;
  anneeCreation: number;
  prixChallenge: number; // à partir de
  profitSplit: number; // %
  drawdownType: 'EOD' | 'Trailing' | 'Static' | 'Hybride';
  newsTrading: boolean;
  smcAllowed: boolean;
  eaAllowed: boolean;
  payoutDelay: number; // jours moyen
  incidents: number;
  incidentsDetails?: string[];
  style: string[]; // SMC, Scalp, Swing, EA, Copy
  legalVerified: boolean;
  transparencyScore: number; // 0-20 internal
  payoutProof: boolean;
  recentRuleChange: boolean;
};

export const propFirms: PropFirm[] = [
  {
    id: 1,
    slug: 'ftmo',
    name: 'FTMO',
    status: 'Active',
    score: 87,
    anneeCreation: 2015,
    prixChallenge: 155,
    profitSplit: 80,
    drawdownType: 'EOD',
    newsTrading: true,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 1,
    incidents: 2,
    incidentsDetails: ['Plainte sur délai payout en 2023 (résolu)', 'Changement mineur de scaling plan'],
    style: ['SMC', 'Scalp', 'Swing', 'EA'],
    legalVerified: true,
    transparencyScore: 18,
    payoutProof: true,
    recentRuleChange: false,
  },
  {
    id: 2,
    slug: 'the5ers',
    name: 'The5ers',
    status: 'Active',
    score: 82,
    anneeCreation: 2016,
    prixChallenge: 95,
    profitSplit: 80,
    drawdownType: 'Static',
    newsTrading: false,
    smcAllowed: true,
    eaAllowed: false,
    payoutDelay: 2,
    incidents: 1,
    incidentsDetails: ['Changement de profit split sur certains plans en 2024'],
    style: ['Swing', 'SMC'],
    legalVerified: true,
    transparencyScore: 17,
    payoutProof: true,
    recentRuleChange: true,
  },
  {
    id: 3,
    slug: 'apex-trader-funding',
    name: 'Apex Trader Funding',
    status: 'Active',
    score: 71,
    anneeCreation: 2021,
    prixChallenge: 147,
    profitSplit: 90,
    drawdownType: 'Trailing',
    newsTrading: true,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 3,
    incidents: 4,
    incidentsDetails: ['Plusieurs plaintes payout >7 jours en 2025', 'Changement trailing rules rétroactif signalé'],
    style: ['Scalp', 'SMC', 'EA'],
    legalVerified: false,
    transparencyScore: 12,
    payoutProof: false,
    recentRuleChange: true,
  },
  {
    id: 4,
    slug: 'fundednext',
    name: 'FundedNext',
    status: 'Risque',
    score: 58,
    anneeCreation: 2022,
    prixChallenge: 49,
    profitSplit: 80,
    drawdownType: 'EOD',
    newsTrading: true,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 5,
    incidents: 6,
    incidentsDetails: ['Nombreux retards payout 2024-2025', 'Changement de conditions sans préavis'],
    style: ['SMC', 'Scalp', 'EA', 'Copy'],
    legalVerified: false,
    transparencyScore: 9,
    payoutProof: false,
    recentRuleChange: true,
  },
  {
    id: 5,
    slug: 'blue-guardian',
    name: 'Blue Guardian',
    status: 'Active',
    score: 79,
    anneeCreation: 2022,
    prixChallenge: 85,
    profitSplit: 85,
    drawdownType: 'Trailing',
    newsTrading: true,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 2,
    incidents: 1,
    incidentsDetails: ['Incident isolé de scaling plan'],
    style: ['SMC', 'Scalp', 'Swing'],
    legalVerified: true,
    transparencyScore: 16,
    payoutProof: true,
    recentRuleChange: false,
  },
  {
    id: 6,
    slug: 'goat-funded-trader',
    name: 'Goat Funded Trader',
    status: 'Active',
    score: 74,
    anneeCreation: 2023,
    prixChallenge: 65,
    profitSplit: 80,
    drawdownType: 'EOD',
    newsTrading: false,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 4,
    incidents: 2,
    incidentsDetails: ['Plaintes sur support lent', 'Un payout bloqué temporairement'],
    style: ['SMC', 'Scalp'],
    legalVerified: false,
    transparencyScore: 13,
    payoutProof: true,
    recentRuleChange: false,
  },
  {
    id: 7,
    slug: 'funderpro',
    name: 'FunderPro',
    status: 'Active',
    score: 68,
    anneeCreation: 2022,
    prixChallenge: 55,
    profitSplit: 75,
    drawdownType: 'Static',
    newsTrading: true,
    smcAllowed: true,
    eaAllowed: false,
    payoutDelay: 7,
    incidents: 3,
    incidentsDetails: ['Retards payout récurrents', 'Support peu réactif'],
    style: ['Swing', 'SMC'],
    legalVerified: true,
    transparencyScore: 11,
    payoutProof: false,
    recentRuleChange: true,
  },
  {
    id: 8,
    slug: 'e8-markets',
    name: 'E8 Markets',
    status: 'Active',
    score: 76,
    anneeCreation: 2021,
    prixChallenge: 78,
    profitSplit: 80,
    drawdownType: 'Trailing',
    newsTrading: true,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 2,
    incidents: 2,
    incidentsDetails: ['Changement de drawdown type en 2024'],
    style: ['SMC', 'Scalp', 'EA'],
    legalVerified: true,
    transparencyScore: 15,
    payoutProof: true,
    recentRuleChange: false,
  },
  {
    id: 9,
    slug: 'wegetfunded',
    name: 'WeGetFunded',
    status: 'Risque',
    score: 52,
    anneeCreation: 2023,
    prixChallenge: 39,
    profitSplit: 70,
    drawdownType: 'EOD',
    newsTrading: true,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 8,
    incidents: 5,
    incidentsDetails: ['Plusieurs non-paiements signalés', 'Fermeture de comptes sans raison claire'],
    style: ['SMC', 'Scalp', 'Copy'],
    legalVerified: false,
    transparencyScore: 7,
    payoutProof: false,
    recentRuleChange: true,
  },
  {
    id: 10,
    slug: 'myfundedfx',
    name: 'MyFundedFX',
    status: 'Active',
    score: 65,
    anneeCreation: 2022,
    prixChallenge: 45,
    profitSplit: 75,
    drawdownType: 'Static',
    newsTrading: false,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 5,
    incidents: 3,
    incidentsDetails: ['Retards payout', 'Changement scaling sans communication'],
    style: ['SMC', 'Scalp'],
    legalVerified: true,
    transparencyScore: 10,
    payoutProof: false,
    recentRuleChange: false,
  },
  // CLOSED FIRMS
  {
    id: 11,
    slug: 'my-forex-funds',
    name: 'My Forex Funds',
    status: 'Fermée',
    score: 12,
    anneeCreation: 2020,
    prixChallenge: 49,
    profitSplit: 85,
    drawdownType: 'Trailing',
    newsTrading: true,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 14,
    incidents: 12,
    incidentsDetails: ['Faillite brutale 2023', 'Des milliers de traders non payés', 'Poursuites judiciaires en cours'],
    style: ['SMC', 'Scalp', 'EA'],
    legalVerified: false,
    transparencyScore: 3,
    payoutProof: false,
    recentRuleChange: true,
  },
  {
    id: 12,
    slug: 'the-funded-trader',
    name: 'The Funded Trader',
    status: 'Fermée',
    score: 8,
    anneeCreation: 2021,
    prixChallenge: 59,
    profitSplit: 80,
    drawdownType: 'EOD',
    newsTrading: true,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 10,
    incidents: 9,
    incidentsDetails: ['Fermeture soudaine 2024', 'Non-paiement massif', 'Changement de règles rétroactif avant fermeture'],
    style: ['SMC', 'Scalp', 'EA', 'Copy'],
    legalVerified: false,
    transparencyScore: 2,
    payoutProof: false,
    recentRuleChange: true,
  },
  {
    id: 13,
    slug: 'fidelcrest',
    name: 'Fidelcrest',
    status: 'Fermée',
    score: 19,
    anneeCreation: 2018,
    prixChallenge: 89,
    profitSplit: 80,
    drawdownType: 'Static',
    newsTrading: false,
    smcAllowed: false,
    eaAllowed: true,
    payoutDelay: 21,
    incidents: 7,
    incidentsDetails: ['Problèmes de paiement chroniques', 'Fermeture progressive 2025'],
    style: ['Swing'],
    legalVerified: true,
    transparencyScore: 5,
    payoutProof: false,
    recentRuleChange: true,
  },
  {
    id: 14,
    slug: 'surgetrader',
    name: 'SurgeTrader',
    status: 'Fermée',
    score: 14,
    anneeCreation: 2020,
    prixChallenge: 75,
    profitSplit: 75,
    drawdownType: 'Trailing',
    newsTrading: true,
    smcAllowed: true,
    eaAllowed: true,
    payoutDelay: 12,
    incidents: 8,
    incidentsDetails: ['Faillite 2025', 'Traders bloqués sur payouts', 'Communication mensongère avant fermeture'],
    style: ['SMC', 'Scalp', 'EA'],
    legalVerified: false,
    transparencyScore: 4,
    payoutProof: false,
    recentRuleChange: true,
  },
];

// Scoring function (can be used for future dynamic calc)
export function calculatePropRadarScore(firm: Omit<PropFirm, 'score'>): number {
  let score = 0;
  
  // Ancienneté
  const years = 2026 - firm.anneeCreation;
  if (years >= 2) score += 20;
  else if (years >= 1) score += 10;
  
  // Transparence
  score += firm.transparencyScore || 0;
  
  // Preuve payouts
  if (firm.payoutProof) score += 20;
  
  // Incidents
  score -= firm.incidents * 15;
  
  // Changement rétroactif récent
  if (firm.recentRuleChange) score -= 25;
  
  // Présence légale
  if (firm.legalVerified) score += 10;
  
  // Support (proxy via payout delay for demo)
  if (firm.payoutDelay <= 2) score += 10;
  else if (firm.payoutDelay <= 4) score += 5;
  
  return Math.max(0, Math.min(100, Math.round(score)));
}
